
    import * as Maquette from "maquette";

    export default class BaseStyles {
        public chain: string[];
        public conditions: boolean[] = [];
        public classProps: any = {};
        private writeConditionIndex: number = 0;
        private readConditionIndex: number = 0;
        private classObjectMode: boolean = false;

        constructor(selector: string) {
            this.chain = new Array<string>();
            if (selector.length > 0) {
                this.chain.push(selector);
            }
            return this;
        }

        public when = (condition: boolean): BaseStyles => {
            this.classObjectMode = true;
            this.conditions[this.writeConditionIndex] = condition;
            return this;
        }

        public andWhen = (condition: boolean): BaseStyles => {
            this.classObjectMode = true;
            this.writeConditionIndex++;
            this.readConditionIndex++;
            return this.when(condition);

        }

        public otherwise = (): BaseStyles => {
            this.classObjectMode = true;
            return this.andWhen( !this.conditions[this.readConditionIndex]);
        }

        public h = (properties?: Maquette.VNodeProperties, children?: (string | Maquette.VNode | Maquette.VNodeChild)[]): Maquette.VNode => {
            if (this.classObjectMode) {
                throw Error("You can't build a vnode when you are using this for building a classes object");
            }
            if (typeof properties === "object" && properties.length > 0) {
                return Maquette.h(this.toString(), properties);
            }
            return Maquette.h(this.toString(), properties, children);
        }

        public toObj = () => {
            if (!this.classObjectMode) {
                // tslint:disable-next-line:max-line-length
                throw Error("You need to call at least one conditional method in order to use this as a classes object generator");
            }
            return this.classProps;
        }

        get div(): BaseStyles { return new BaseStyles("div"); }
        get span(): BaseStyles { return new BaseStyles("span"); }
        get button(): BaseStyles { return new BaseStyles("button.btn"); }
        get input(): BaseStyles { return new BaseStyles("input.input"); }
        get label(): BaseStyles { return new BaseStyles("label.label"); }
        get select(): BaseStyles { return new BaseStyles("select.select"); }
        get textarea(): BaseStyles { return new BaseStyles("textarea.textarea"); }

        public toString = (): string => {
            if (this.classObjectMode) {
                throw Error("You can't build a selector string when you are calling conditional methods");
            }
            if (this.chain.length === 1) {
                return this.chain[0] || "div";
            }
            return this.chain.join(".");
        }

        public $ = (className: string): BaseStyles => {
            return this.add(className);
        }

        public add = (className: string): BaseStyles => {
            if (this.classObjectMode) {
                this.classProps[className] = this.conditions[this.readConditionIndex];
            } else if (className.length > 0) {
                this.chain.push(className);
            }
            return this;
        }

        get aspectRatio() { return this.add("aspect-ratio"); }
get aspectRatio_16x9() { return this.add("aspect-ratio--16x9"); }
get aspectRatio_9x16() { return this.add("aspect-ratio--9x16"); }
get aspectRatio_4x3() { return this.add("aspect-ratio--4x3"); }
get aspectRatio_3x4() { return this.add("aspect-ratio--3x4"); }
get aspectRatio_6x4() { return this.add("aspect-ratio--6x4"); }
get aspectRatio_4x6() { return this.add("aspect-ratio--4x6"); }
get aspectRatio_8x5() { return this.add("aspect-ratio--8x5"); }
get aspectRatio_5x8() { return this.add("aspect-ratio--5x8"); }
get aspectRatio_7x5() { return this.add("aspect-ratio--7x5"); }
get aspectRatio_5x7() { return this.add("aspect-ratio--5x7"); }
get aspectRatio_1x1() { return this.add("aspect-ratio--1x1"); }
get aspectRatioObject() { return this.add("aspect-ratio--object"); }
get cover() { return this.add("cover"); }
get contain() { return this.add("contain"); }
get bgCenter() { return this.add("bg-center"); }
get bgTop() { return this.add("bg-top"); }
get bgRight() { return this.add("bg-right"); }
get bgBottom() { return this.add("bg-bottom"); }
get bgLeft() { return this.add("bg-left"); }
get outline() { return this.add("outline"); }
get outlineTransparent() { return this.add("outline-transparent"); }
get outline_0() { return this.add("outline-0"); }
get ba() { return this.add("ba"); }
get bt() { return this.add("bt"); }
get br() { return this.add("br"); }
get bb() { return this.add("bb"); }
get bl() { return this.add("bl"); }
get bn() { return this.add("bn"); }
get bBlack() { return this.add("b--black"); }
get bNearBlack() { return this.add("b--near-black"); }
get bDarkGray() { return this.add("b--dark-gray"); }
get bMidGray() { return this.add("b--mid-gray"); }
get bGray() { return this.add("b--gray"); }
get bSilver() { return this.add("b--silver"); }
get bLightSilver() { return this.add("b--light-silver"); }
get bMoonGray() { return this.add("b--moon-gray"); }
get bLightGray() { return this.add("b--light-gray"); }
get bNearWhite() { return this.add("b--near-white"); }
get bWhite() { return this.add("b--white"); }
get bWhite_90() { return this.add("b--white-90"); }
get bWhite_80() { return this.add("b--white-80"); }
get bWhite_70() { return this.add("b--white-70"); }
get bWhite_60() { return this.add("b--white-60"); }
get bWhite_50() { return this.add("b--white-50"); }
get bWhite_40() { return this.add("b--white-40"); }
get bWhite_30() { return this.add("b--white-30"); }
get bWhite_20() { return this.add("b--white-20"); }
get bWhite_10() { return this.add("b--white-10"); }
get bWhite_05() { return this.add("b--white-05"); }
get bWhite_025() { return this.add("b--white-025"); }
get bWhite_0125() { return this.add("b--white-0125"); }
get bBlack_90() { return this.add("b--black-90"); }
get bBlack_80() { return this.add("b--black-80"); }
get bBlack_70() { return this.add("b--black-70"); }
get bBlack_60() { return this.add("b--black-60"); }
get bBlack_50() { return this.add("b--black-50"); }
get bBlack_40() { return this.add("b--black-40"); }
get bBlack_30() { return this.add("b--black-30"); }
get bBlack_20() { return this.add("b--black-20"); }
get bBlack_10() { return this.add("b--black-10"); }
get bBlack_05() { return this.add("b--black-05"); }
get bBlack_025() { return this.add("b--black-025"); }
get bBlack_0125() { return this.add("b--black-0125"); }
get bDarkRed() { return this.add("b--dark-red"); }
get bRed() { return this.add("b--red"); }
get bLightRed() { return this.add("b--light-red"); }
get bOrange() { return this.add("b--orange"); }
get bGold() { return this.add("b--gold"); }
get bYellow() { return this.add("b--yellow"); }
get bLightYellow() { return this.add("b--light-yellow"); }
get bPurple() { return this.add("b--purple"); }
get bLightPurple() { return this.add("b--light-purple"); }
get bDarkPink() { return this.add("b--dark-pink"); }
get bHotPink() { return this.add("b--hot-pink"); }
get bPink() { return this.add("b--pink"); }
get bLightPink() { return this.add("b--light-pink"); }
get bDarkGreen() { return this.add("b--dark-green"); }
get bGreen() { return this.add("b--green"); }
get bLightGreen() { return this.add("b--light-green"); }
get bNavy() { return this.add("b--navy"); }
get bDarkBlue() { return this.add("b--dark-blue"); }
get bBlue() { return this.add("b--blue"); }
get bLightBlue() { return this.add("b--light-blue"); }
get bLightestBlue() { return this.add("b--lightest-blue"); }
get bWashedBlue() { return this.add("b--washed-blue"); }
get bWashedGreen() { return this.add("b--washed-green"); }
get bWashedYellow() { return this.add("b--washed-yellow"); }
get bWashedRed() { return this.add("b--washed-red"); }
get bTransparent() { return this.add("b--transparent"); }
get bInherit() { return this.add("b--inherit"); }
get br0() { return this.add("br0"); }
get br1() { return this.add("br1"); }
get br2() { return this.add("br2"); }
get br3() { return this.add("br3"); }
get br4() { return this.add("br4"); }
get br_100() { return this.add("br-100"); }
get brPill() { return this.add("br-pill"); }
get brBottom() { return this.add("br--bottom"); }
get brTop() { return this.add("br--top"); }
get brRight() { return this.add("br--right"); }
get brLeft() { return this.add("br--left"); }
get bDotted() { return this.add("b--dotted"); }
get bDashed() { return this.add("b--dashed"); }
get bSolid() { return this.add("b--solid"); }
get bNone() { return this.add("b--none"); }
get bw0() { return this.add("bw0"); }
get bw1() { return this.add("bw1"); }
get bw2() { return this.add("bw2"); }
get bw3() { return this.add("bw3"); }
get bw4() { return this.add("bw4"); }
get bw5() { return this.add("bw5"); }
get bt_0() { return this.add("bt-0"); }
get br_0() { return this.add("br-0"); }
get bb_0() { return this.add("bb-0"); }
get bl_0() { return this.add("bl-0"); }
get shadow_1() { return this.add("shadow-1"); }
get shadow_2() { return this.add("shadow-2"); }
get shadow_3() { return this.add("shadow-3"); }
get shadow_4() { return this.add("shadow-4"); }
get shadow_5() { return this.add("shadow-5"); }
get pre() { return this.add("pre"); }
get top_0() { return this.add("top-0"); }
get right_0() { return this.add("right-0"); }
get bottom_0() { return this.add("bottom-0"); }
get left_0() { return this.add("left-0"); }
get top_1() { return this.add("top-1"); }
get right_1() { return this.add("right-1"); }
get bottom_1() { return this.add("bottom-1"); }
get left_1() { return this.add("left-1"); }
get top_2() { return this.add("top-2"); }
get right_2() { return this.add("right-2"); }
get bottom_2() { return this.add("bottom-2"); }
get left_2() { return this.add("left-2"); }
get absoluteFill() { return this.add("absolute--fill"); }
get cf() { return this.add("cf"); }
get cl() { return this.add("cl"); }
get cr() { return this.add("cr"); }
get cb() { return this.add("cb"); }
get cn() { return this.add("cn"); }
get dn() { return this.add("dn"); }
get di() { return this.add("di"); }
get db() { return this.add("db"); }
get dib() { return this.add("dib"); }
get dit() { return this.add("dit"); }
get dt() { return this.add("dt"); }
get dtc() { return this.add("dtc"); }
get dtRow() { return this.add("dt-row"); }
get dtRowGroup() { return this.add("dt-row-group"); }
get dtColumn() { return this.add("dt-column"); }
get dtColumnGroup() { return this.add("dt-column-group"); }
get dtFixed() { return this.add("dt--fixed"); }
get flex() { return this.add("flex"); }
get inlineFlex() { return this.add("inline-flex"); }
get flexAuto() { return this.add("flex-auto"); }
get flexNone() { return this.add("flex-none"); }
get flexColumn() { return this.add("flex-column"); }
get flexRow() { return this.add("flex-row"); }
get flexWrap() { return this.add("flex-wrap"); }
get flexNowrap() { return this.add("flex-nowrap"); }
get flexWrapReverse() { return this.add("flex-wrap-reverse"); }
get flexColumnReverse() { return this.add("flex-column-reverse"); }
get flexRowReverse() { return this.add("flex-row-reverse"); }
get itemsStart() { return this.add("items-start"); }
get itemsEnd() { return this.add("items-end"); }
get itemsCenter() { return this.add("items-center"); }
get itemsBaseline() { return this.add("items-baseline"); }
get itemsStretch() { return this.add("items-stretch"); }
get selfStart() { return this.add("self-start"); }
get selfEnd() { return this.add("self-end"); }
get selfCenter() { return this.add("self-center"); }
get selfBaseline() { return this.add("self-baseline"); }
get selfStretch() { return this.add("self-stretch"); }
get justifyStart() { return this.add("justify-start"); }
get justifyEnd() { return this.add("justify-end"); }
get justifyCenter() { return this.add("justify-center"); }
get justifyBetween() { return this.add("justify-between"); }
get justifyAround() { return this.add("justify-around"); }
get contentStart() { return this.add("content-start"); }
get contentEnd() { return this.add("content-end"); }
get contentCenter() { return this.add("content-center"); }
get contentBetween() { return this.add("content-between"); }
get contentAround() { return this.add("content-around"); }
get contentStretch() { return this.add("content-stretch"); }
get order_0() { return this.add("order-0"); }
get order_1() { return this.add("order-1"); }
get order_2() { return this.add("order-2"); }
get order_3() { return this.add("order-3"); }
get order_4() { return this.add("order-4"); }
get order_5() { return this.add("order-5"); }
get order_6() { return this.add("order-6"); }
get order_7() { return this.add("order-7"); }
get order_8() { return this.add("order-8"); }
get orderLast() { return this.add("order-last"); }
get flexGrow_0() { return this.add("flex-grow-0"); }
get flexGrow_1() { return this.add("flex-grow-1"); }
get flexShrink_0() { return this.add("flex-shrink-0"); }
get flexShrink_1() { return this.add("flex-shrink-1"); }
get fl() { return this.add("fl"); }
get fr() { return this.add("fr"); }
get fn() { return this.add("fn"); }
get sansSerif() { return this.add("sans-serif"); }
get serif() { return this.add("serif"); }
get systemSansSerif() { return this.add("system-sans-serif"); }
get systemSerif() { return this.add("system-serif"); }
get courier() { return this.add("courier"); }
get helvetica() { return this.add("helvetica"); }
get avenir() { return this.add("avenir"); }
get athelas() { return this.add("athelas"); }
get georgia() { return this.add("georgia"); }
get times() { return this.add("times"); }
get bodoni() { return this.add("bodoni"); }
get calisto() { return this.add("calisto"); }
get garamond() { return this.add("garamond"); }
get baskerville() { return this.add("baskerville"); }
get i() { return this.add("i"); }
get fsNormal() { return this.add("fs-normal"); }
get normal() { return this.add("normal"); }
get b() { return this.add("b"); }
get fw1() { return this.add("fw1"); }
get fw2() { return this.add("fw2"); }
get fw3() { return this.add("fw3"); }
get fw4() { return this.add("fw4"); }
get fw5() { return this.add("fw5"); }
get fw6() { return this.add("fw6"); }
get fw7() { return this.add("fw7"); }
get fw8() { return this.add("fw8"); }
get fw9() { return this.add("fw9"); }
get inputReset() { return this.add("input-reset"); }
get h1() { return this.add("h1"); }
get h2() { return this.add("h2"); }
get h3() { return this.add("h3"); }
get h4() { return this.add("h4"); }
get h5() { return this.add("h5"); }
get h_25() { return this.add("h-25"); }
get h_50() { return this.add("h-50"); }
get h_75() { return this.add("h-75"); }
get h_100() { return this.add("h-100"); }
get minH_100() { return this.add("min-h-100"); }
get vh_25() { return this.add("vh-25"); }
get vh_50() { return this.add("vh-50"); }
get vh_75() { return this.add("vh-75"); }
get vh_100() { return this.add("vh-100"); }
get minVh_100() { return this.add("min-vh-100"); }
get hAuto() { return this.add("h-auto"); }
get hInherit() { return this.add("h-inherit"); }
get tracked() { return this.add("tracked"); }
get trackedTight() { return this.add("tracked-tight"); }
get trackedMega() { return this.add("tracked-mega"); }
get lhSolid() { return this.add("lh-solid"); }
get lhTitle() { return this.add("lh-title"); }
get lhCopy() { return this.add("lh-copy"); }
get Link() { return this.add("link"); }
get list() { return this.add("list"); }
get mw_100() { return this.add("mw-100"); }
get mw1() { return this.add("mw1"); }
get mw2() { return this.add("mw2"); }
get mw3() { return this.add("mw3"); }
get mw4() { return this.add("mw4"); }
get mw5() { return this.add("mw5"); }
get mw6() { return this.add("mw6"); }
get mw7() { return this.add("mw7"); }
get mw8() { return this.add("mw8"); }
get mw9() { return this.add("mw9"); }
get mwNone() { return this.add("mw-none"); }
get w1() { return this.add("w1"); }
get w2() { return this.add("w2"); }
get w3() { return this.add("w3"); }
get w4() { return this.add("w4"); }
get w5() { return this.add("w5"); }
get w_10() { return this.add("w-10"); }
get w_20() { return this.add("w-20"); }
get w_25() { return this.add("w-25"); }
get w_30() { return this.add("w-30"); }
get w_33() { return this.add("w-33"); }
get w_34() { return this.add("w-34"); }
get w_40() { return this.add("w-40"); }
get w_50() { return this.add("w-50"); }
get w_60() { return this.add("w-60"); }
get w_70() { return this.add("w-70"); }
get w_75() { return this.add("w-75"); }
get w_80() { return this.add("w-80"); }
get w_90() { return this.add("w-90"); }
get w_100() { return this.add("w-100"); }
get wThird() { return this.add("w-third"); }
get wTwoThirds() { return this.add("w-two-thirds"); }
get wAuto() { return this.add("w-auto"); }
get overflowVisible() { return this.add("overflow-visible"); }
get overflowHidden() { return this.add("overflow-hidden"); }
get overflowScroll() { return this.add("overflow-scroll"); }
get overflowAuto() { return this.add("overflow-auto"); }
get overflowXVisible() { return this.add("overflow-x-visible"); }
get overflowXHidden() { return this.add("overflow-x-hidden"); }
get overflowXScroll() { return this.add("overflow-x-scroll"); }
get overflowXAuto() { return this.add("overflow-x-auto"); }
get overflowYVisible() { return this.add("overflow-y-visible"); }
get overflowYHidden() { return this.add("overflow-y-hidden"); }
get overflowYScroll() { return this.add("overflow-y-scroll"); }
get overflowYAuto() { return this.add("overflow-y-auto"); }
get static() { return this.add("static"); }
get relative() { return this.add("relative"); }
get absolute() { return this.add("absolute"); }
get Fixed() { return this.add("fixed"); }
get o_100() { return this.add("o-100"); }
get o_90() { return this.add("o-90"); }
get o_80() { return this.add("o-80"); }
get o_70() { return this.add("o-70"); }
get o_60() { return this.add("o-60"); }
get o_50() { return this.add("o-50"); }
get o_40() { return this.add("o-40"); }
get o_30() { return this.add("o-30"); }
get o_20() { return this.add("o-20"); }
get o_10() { return this.add("o-10"); }
get o_05() { return this.add("o-05"); }
get o_025() { return this.add("o-025"); }
get o_0() { return this.add("o-0"); }
get rotate_45() { return this.add("rotate-45"); }
get rotate_90() { return this.add("rotate-90"); }
get rotate_135() { return this.add("rotate-135"); }
get rotate_180() { return this.add("rotate-180"); }
get rotate_225() { return this.add("rotate-225"); }
get rotate_270() { return this.add("rotate-270"); }
get rotate_315() { return this.add("rotate-315"); }
get black_90() { return this.add("black-90"); }
get black_80() { return this.add("black-80"); }
get black_70() { return this.add("black-70"); }
get black_60() { return this.add("black-60"); }
get black_50() { return this.add("black-50"); }
get black_40() { return this.add("black-40"); }
get black_30() { return this.add("black-30"); }
get black_20() { return this.add("black-20"); }
get black_10() { return this.add("black-10"); }
get black_05() { return this.add("black-05"); }
get white_90() { return this.add("white-90"); }
get white_80() { return this.add("white-80"); }
get white_70() { return this.add("white-70"); }
get white_60() { return this.add("white-60"); }
get white_50() { return this.add("white-50"); }
get white_40() { return this.add("white-40"); }
get white_30() { return this.add("white-30"); }
get white_20() { return this.add("white-20"); }
get white_10() { return this.add("white-10"); }
get black() { return this.add("black"); }
get nearBlack() { return this.add("near-black"); }
get darkGray() { return this.add("dark-gray"); }
get midGray() { return this.add("mid-gray"); }
get gray() { return this.add("gray"); }
get silver() { return this.add("silver"); }
get lightSilver() { return this.add("light-silver"); }
get moonGray() { return this.add("moon-gray"); }
get lightGray() { return this.add("light-gray"); }
get nearWhite() { return this.add("near-white"); }
get white() { return this.add("white"); }
get darkRed() { return this.add("dark-red"); }
get red() { return this.add("red"); }
get lightRed() { return this.add("light-red"); }
get orange() { return this.add("orange"); }
get gold() { return this.add("gold"); }
get yellow() { return this.add("yellow"); }
get lightYellow() { return this.add("light-yellow"); }
get purple() { return this.add("purple"); }
get lightPurple() { return this.add("light-purple"); }
get darkPink() { return this.add("dark-pink"); }
get hotPink() { return this.add("hot-pink"); }
get pink() { return this.add("pink"); }
get lightPink() { return this.add("light-pink"); }
get darkGreen() { return this.add("dark-green"); }
get green() { return this.add("green"); }
get lightGreen() { return this.add("light-green"); }
get navy() { return this.add("navy"); }
get darkBlue() { return this.add("dark-blue"); }
get blue() { return this.add("blue"); }
get lightBlue() { return this.add("light-blue"); }
get lightestBlue() { return this.add("lightest-blue"); }
get washedBlue() { return this.add("washed-blue"); }
get washedGreen() { return this.add("washed-green"); }
get washedYellow() { return this.add("washed-yellow"); }
get washedRed() { return this.add("washed-red"); }
get colorInherit() { return this.add("color-inherit"); }
get bgBlack_90() { return this.add("bg-black-90"); }
get bgBlack_80() { return this.add("bg-black-80"); }
get bgBlack_70() { return this.add("bg-black-70"); }
get bgBlack_60() { return this.add("bg-black-60"); }
get bgBlack_50() { return this.add("bg-black-50"); }
get bgBlack_40() { return this.add("bg-black-40"); }
get bgBlack_30() { return this.add("bg-black-30"); }
get bgBlack_20() { return this.add("bg-black-20"); }
get bgBlack_10() { return this.add("bg-black-10"); }
get bgBlack_05() { return this.add("bg-black-05"); }
get bgWhite_90() { return this.add("bg-white-90"); }
get bgWhite_80() { return this.add("bg-white-80"); }
get bgWhite_70() { return this.add("bg-white-70"); }
get bgWhite_60() { return this.add("bg-white-60"); }
get bgWhite_50() { return this.add("bg-white-50"); }
get bgWhite_40() { return this.add("bg-white-40"); }
get bgWhite_30() { return this.add("bg-white-30"); }
get bgWhite_20() { return this.add("bg-white-20"); }
get bgWhite_10() { return this.add("bg-white-10"); }
get bgBlack() { return this.add("bg-black"); }
get bgNearBlack() { return this.add("bg-near-black"); }
get bgDarkGray() { return this.add("bg-dark-gray"); }
get bgMidGray() { return this.add("bg-mid-gray"); }
get bgGray() { return this.add("bg-gray"); }
get bgSilver() { return this.add("bg-silver"); }
get bgLightSilver() { return this.add("bg-light-silver"); }
get bgMoonGray() { return this.add("bg-moon-gray"); }
get bgLightGray() { return this.add("bg-light-gray"); }
get bgNearWhite() { return this.add("bg-near-white"); }
get bgWhite() { return this.add("bg-white"); }
get bgTransparent() { return this.add("bg-transparent"); }
get bgDarkRed() { return this.add("bg-dark-red"); }
get bgRed() { return this.add("bg-red"); }
get bgLightRed() { return this.add("bg-light-red"); }
get bgOrange() { return this.add("bg-orange"); }
get bgGold() { return this.add("bg-gold"); }
get bgYellow() { return this.add("bg-yellow"); }
get bgLightYellow() { return this.add("bg-light-yellow"); }
get bgPurple() { return this.add("bg-purple"); }
get bgLightPurple() { return this.add("bg-light-purple"); }
get bgDarkPink() { return this.add("bg-dark-pink"); }
get bgHotPink() { return this.add("bg-hot-pink"); }
get bgPink() { return this.add("bg-pink"); }
get bgLightPink() { return this.add("bg-light-pink"); }
get bgDarkGreen() { return this.add("bg-dark-green"); }
get bgGreen() { return this.add("bg-green"); }
get bgLightGreen() { return this.add("bg-light-green"); }
get bgNavy() { return this.add("bg-navy"); }
get bgDarkBlue() { return this.add("bg-dark-blue"); }
get bgBlue() { return this.add("bg-blue"); }
get bgLightBlue() { return this.add("bg-light-blue"); }
get bgLightestBlue() { return this.add("bg-lightest-blue"); }
get bgWashedBlue() { return this.add("bg-washed-blue"); }
get bgWashedGreen() { return this.add("bg-washed-green"); }
get bgWashedYellow() { return this.add("bg-washed-yellow"); }
get bgWashedRed() { return this.add("bg-washed-red"); }
get bgInherit() { return this.add("bg-inherit"); }
get pa0() { return this.add("pa0"); }
get pa1() { return this.add("pa1"); }
get pa2() { return this.add("pa2"); }
get pa3() { return this.add("pa3"); }
get pa4() { return this.add("pa4"); }
get pa5() { return this.add("pa5"); }
get pa6() { return this.add("pa6"); }
get pa7() { return this.add("pa7"); }
get pl0() { return this.add("pl0"); }
get pl1() { return this.add("pl1"); }
get pl2() { return this.add("pl2"); }
get pl3() { return this.add("pl3"); }
get pl4() { return this.add("pl4"); }
get pl5() { return this.add("pl5"); }
get pl6() { return this.add("pl6"); }
get pl7() { return this.add("pl7"); }
get pr0() { return this.add("pr0"); }
get pr1() { return this.add("pr1"); }
get pr2() { return this.add("pr2"); }
get pr3() { return this.add("pr3"); }
get pr4() { return this.add("pr4"); }
get pr5() { return this.add("pr5"); }
get pr6() { return this.add("pr6"); }
get pr7() { return this.add("pr7"); }
get pb0() { return this.add("pb0"); }
get pb1() { return this.add("pb1"); }
get pb2() { return this.add("pb2"); }
get pb3() { return this.add("pb3"); }
get pb4() { return this.add("pb4"); }
get pb5() { return this.add("pb5"); }
get pb6() { return this.add("pb6"); }
get pb7() { return this.add("pb7"); }
get pt0() { return this.add("pt0"); }
get pt1() { return this.add("pt1"); }
get pt2() { return this.add("pt2"); }
get pt3() { return this.add("pt3"); }
get pt4() { return this.add("pt4"); }
get pt5() { return this.add("pt5"); }
get pt6() { return this.add("pt6"); }
get pt7() { return this.add("pt7"); }
get pv0() { return this.add("pv0"); }
get pv1() { return this.add("pv1"); }
get pv2() { return this.add("pv2"); }
get pv3() { return this.add("pv3"); }
get pv4() { return this.add("pv4"); }
get pv5() { return this.add("pv5"); }
get pv6() { return this.add("pv6"); }
get pv7() { return this.add("pv7"); }
get ph0() { return this.add("ph0"); }
get ph1() { return this.add("ph1"); }
get ph2() { return this.add("ph2"); }
get ph3() { return this.add("ph3"); }
get ph4() { return this.add("ph4"); }
get ph5() { return this.add("ph5"); }
get ph6() { return this.add("ph6"); }
get ph7() { return this.add("ph7"); }
get ma0() { return this.add("ma0"); }
get ma1() { return this.add("ma1"); }
get ma2() { return this.add("ma2"); }
get ma3() { return this.add("ma3"); }
get ma4() { return this.add("ma4"); }
get ma5() { return this.add("ma5"); }
get ma6() { return this.add("ma6"); }
get ma7() { return this.add("ma7"); }
get ml0() { return this.add("ml0"); }
get ml1() { return this.add("ml1"); }
get ml2() { return this.add("ml2"); }
get ml3() { return this.add("ml3"); }
get ml4() { return this.add("ml4"); }
get ml5() { return this.add("ml5"); }
get ml6() { return this.add("ml6"); }
get ml7() { return this.add("ml7"); }
get mr0() { return this.add("mr0"); }
get mr1() { return this.add("mr1"); }
get mr2() { return this.add("mr2"); }
get mr3() { return this.add("mr3"); }
get mr4() { return this.add("mr4"); }
get mr5() { return this.add("mr5"); }
get mr6() { return this.add("mr6"); }
get mr7() { return this.add("mr7"); }
get mb0() { return this.add("mb0"); }
get mb1() { return this.add("mb1"); }
get mb2() { return this.add("mb2"); }
get mb3() { return this.add("mb3"); }
get mb4() { return this.add("mb4"); }
get mb5() { return this.add("mb5"); }
get mb6() { return this.add("mb6"); }
get mb7() { return this.add("mb7"); }
get mt0() { return this.add("mt0"); }
get mt1() { return this.add("mt1"); }
get mt2() { return this.add("mt2"); }
get mt3() { return this.add("mt3"); }
get mt4() { return this.add("mt4"); }
get mt5() { return this.add("mt5"); }
get mt6() { return this.add("mt6"); }
get mt7() { return this.add("mt7"); }
get mv0() { return this.add("mv0"); }
get mv1() { return this.add("mv1"); }
get mv2() { return this.add("mv2"); }
get mv3() { return this.add("mv3"); }
get mv4() { return this.add("mv4"); }
get mv5() { return this.add("mv5"); }
get mv6() { return this.add("mv6"); }
get mv7() { return this.add("mv7"); }
get mh0() { return this.add("mh0"); }
get mh1() { return this.add("mh1"); }
get mh2() { return this.add("mh2"); }
get mh3() { return this.add("mh3"); }
get mh4() { return this.add("mh4"); }
get mh5() { return this.add("mh5"); }
get mh6() { return this.add("mh6"); }
get mh7() { return this.add("mh7"); }
get na1() { return this.add("na1"); }
get na2() { return this.add("na2"); }
get na3() { return this.add("na3"); }
get na4() { return this.add("na4"); }
get na5() { return this.add("na5"); }
get na6() { return this.add("na6"); }
get na7() { return this.add("na7"); }
get nl1() { return this.add("nl1"); }
get nl2() { return this.add("nl2"); }
get nl3() { return this.add("nl3"); }
get nl4() { return this.add("nl4"); }
get nl5() { return this.add("nl5"); }
get nl6() { return this.add("nl6"); }
get nl7() { return this.add("nl7"); }
get nr1() { return this.add("nr1"); }
get nr2() { return this.add("nr2"); }
get nr3() { return this.add("nr3"); }
get nr4() { return this.add("nr4"); }
get nr5() { return this.add("nr5"); }
get nr6() { return this.add("nr6"); }
get nr7() { return this.add("nr7"); }
get nb1() { return this.add("nb1"); }
get nb2() { return this.add("nb2"); }
get nb3() { return this.add("nb3"); }
get nb4() { return this.add("nb4"); }
get nb5() { return this.add("nb5"); }
get nb6() { return this.add("nb6"); }
get nb7() { return this.add("nb7"); }
get nt1() { return this.add("nt1"); }
get nt2() { return this.add("nt2"); }
get nt3() { return this.add("nt3"); }
get nt4() { return this.add("nt4"); }
get nt5() { return this.add("nt5"); }
get nt6() { return this.add("nt6"); }
get nt7() { return this.add("nt7"); }
get collapse() { return this.add("collapse"); }
get Strike() { return this.add("strike"); }
get underline() { return this.add("underline"); }
get noUnderline() { return this.add("no-underline"); }
get tl() { return this.add("tl"); }
get tr() { return this.add("tr"); }
get tc() { return this.add("tc"); }
get tj() { return this.add("tj"); }
get ttc() { return this.add("ttc"); }
get ttl() { return this.add("ttl"); }
get ttu() { return this.add("ttu"); }
get ttn() { return this.add("ttn"); }
get f_6() { return this.add("f-6"); }
get fHeadline() { return this.add("f-headline"); }
get f_5() { return this.add("f-5"); }
get fSubheadline() { return this.add("f-subheadline"); }
get f1() { return this.add("f1"); }
get f2() { return this.add("f2"); }
get f3() { return this.add("f3"); }
get f4() { return this.add("f4"); }
get f5() { return this.add("f5"); }
get f6() { return this.add("f6"); }
get f7() { return this.add("f7"); }
get measure() { return this.add("measure"); }
get measureWide() { return this.add("measure-wide"); }
get measureNarrow() { return this.add("measure-narrow"); }
get indent() { return this.add("indent"); }
get smallCaps() { return this.add("small-caps"); }
get truncate() { return this.add("truncate"); }
get overflowContainer() { return this.add("overflow-container"); }
get center() { return this.add("center"); }
get mrAuto() { return this.add("mr-auto"); }
get mlAuto() { return this.add("ml-auto"); }
get clip() { return this.add("clip"); }
get wsNormal() { return this.add("ws-normal"); }
get nowrap() { return this.add("nowrap"); }
get vBase() { return this.add("v-base"); }
get vMid() { return this.add("v-mid"); }
get vTop() { return this.add("v-top"); }
get vBtm() { return this.add("v-btm"); }
get dim() { return this.add("dim"); }
get glow() { return this.add("glow"); }
get hideChildChild() { return this.add("hide-child .child"); }
get grow() { return this.add("grow"); }
get growLarge() { return this.add("grow-large"); }
get shadowHover() { return this.add("shadow-hover"); }
get z_0() { return this.add("z-0"); }
get z_1() { return this.add("z-1"); }
get z_2() { return this.add("z-2"); }
get z_3() { return this.add("z-3"); }
get z_4() { return this.add("z-4"); }
get z_5() { return this.add("z-5"); }
get z_999() { return this.add("z-999"); }
get z_9999() { return this.add("z-9999"); }
get zMax() { return this.add("z-max"); }
get zInherit() { return this.add("z-inherit"); }
get zInitial() { return this.add("z-initial"); }
get zUnset() { return this.add("z-unset"); }
get nestedCopyLineHeightP() { return this.add("nested-copy-line-height p"); }
get nestedCopyLineHeightUl() { return this.add("nested-copy-line-height ul"); }
get nestedCopyLineHeightOl() { return this.add("nested-copy-line-height ol"); }
get nestedHeadlineLineHeightH1() { return this.add("nested-headline-line-height h1"); }
get nestedHeadlineLineHeightH2() { return this.add("nested-headline-line-height h2"); }
get nestedHeadlineLineHeightH3() { return this.add("nested-headline-line-height h3"); }
get nestedHeadlineLineHeightH4() { return this.add("nested-headline-line-height h4"); }
get nestedHeadlineLineHeightH5() { return this.add("nested-headline-line-height h5"); }
get nestedHeadlineLineHeightH6() { return this.add("nested-headline-line-height h6"); }
get nestedListResetUl() { return this.add("nested-list-reset ul"); }
get nestedListResetOl() { return this.add("nested-list-reset ol"); }
get nestedImgImg() { return this.add("nested-img img"); }
get nestedLinksA() { return this.add("nested-links a"); }
get debug() { return this.add("debug *"); }
get debugWhite() { return this.add("debug-white *"); }
get debugBlack() { return this.add("debug-black *"); }
get debugGrid() { return this.add("debug-grid"); }
get debugGrid_16() { return this.add("debug-grid-16"); }
get debugGrid_8Solid() { return this.add("debug-grid-8-solid"); }
get debugGrid_16Solid() { return this.add("debug-grid-16-solid"); }
get aspectRatioNs() { return this.add("aspect-ratio-ns"); }
get aspectRatio_16x9Ns() { return this.add("aspect-ratio--16x9-ns"); }
get aspectRatio_9x16Ns() { return this.add("aspect-ratio--9x16-ns"); }
get aspectRatio_4x3Ns() { return this.add("aspect-ratio--4x3-ns"); }
get aspectRatio_3x4Ns() { return this.add("aspect-ratio--3x4-ns"); }
get aspectRatio_6x4Ns() { return this.add("aspect-ratio--6x4-ns"); }
get aspectRatio_4x6Ns() { return this.add("aspect-ratio--4x6-ns"); }
get aspectRatio_8x5Ns() { return this.add("aspect-ratio--8x5-ns"); }
get aspectRatio_5x8Ns() { return this.add("aspect-ratio--5x8-ns"); }
get aspectRatio_7x5Ns() { return this.add("aspect-ratio--7x5-ns"); }
get aspectRatio_5x7Ns() { return this.add("aspect-ratio--5x7-ns"); }
get aspectRatio_1x1Ns() { return this.add("aspect-ratio--1x1-ns"); }
get aspectRatioObjectNs() { return this.add("aspect-ratio--object-ns"); }
get coverNs() { return this.add("cover-ns"); }
get containNs() { return this.add("contain-ns"); }
get bgCenterNs() { return this.add("bg-center-ns"); }
get bgTopNs() { return this.add("bg-top-ns"); }
get bgRightNs() { return this.add("bg-right-ns"); }
get bgBottomNs() { return this.add("bg-bottom-ns"); }
get bgLeftNs() { return this.add("bg-left-ns"); }
get outlineNs() { return this.add("outline-ns"); }
get outlineTransparentNs() { return this.add("outline-transparent-ns"); }
get outline_0Ns() { return this.add("outline-0-ns"); }
get baNs() { return this.add("ba-ns"); }
get btNs() { return this.add("bt-ns"); }
get brNs() { return this.add("br-ns"); }
get bbNs() { return this.add("bb-ns"); }
get blNs() { return this.add("bl-ns"); }
get bnNs() { return this.add("bn-ns"); }
get br0Ns() { return this.add("br0-ns"); }
get br1Ns() { return this.add("br1-ns"); }
get br2Ns() { return this.add("br2-ns"); }
get br3Ns() { return this.add("br3-ns"); }
get br4Ns() { return this.add("br4-ns"); }
get br_100Ns() { return this.add("br-100-ns"); }
get brPillNs() { return this.add("br-pill-ns"); }
get brBottomNs() { return this.add("br--bottom-ns"); }
get brTopNs() { return this.add("br--top-ns"); }
get brRightNs() { return this.add("br--right-ns"); }
get brLeftNs() { return this.add("br--left-ns"); }
get bDottedNs() { return this.add("b--dotted-ns"); }
get bDashedNs() { return this.add("b--dashed-ns"); }
get bSolidNs() { return this.add("b--solid-ns"); }
get bNoneNs() { return this.add("b--none-ns"); }
get bw0Ns() { return this.add("bw0-ns"); }
get bw1Ns() { return this.add("bw1-ns"); }
get bw2Ns() { return this.add("bw2-ns"); }
get bw3Ns() { return this.add("bw3-ns"); }
get bw4Ns() { return this.add("bw4-ns"); }
get bw5Ns() { return this.add("bw5-ns"); }
get bt_0Ns() { return this.add("bt-0-ns"); }
get br_0Ns() { return this.add("br-0-ns"); }
get bb_0Ns() { return this.add("bb-0-ns"); }
get bl_0Ns() { return this.add("bl-0-ns"); }
get shadow_1Ns() { return this.add("shadow-1-ns"); }
get shadow_2Ns() { return this.add("shadow-2-ns"); }
get shadow_3Ns() { return this.add("shadow-3-ns"); }
get shadow_4Ns() { return this.add("shadow-4-ns"); }
get shadow_5Ns() { return this.add("shadow-5-ns"); }
get top_0Ns() { return this.add("top-0-ns"); }
get left_0Ns() { return this.add("left-0-ns"); }
get right_0Ns() { return this.add("right-0-ns"); }
get bottom_0Ns() { return this.add("bottom-0-ns"); }
get top_1Ns() { return this.add("top-1-ns"); }
get left_1Ns() { return this.add("left-1-ns"); }
get right_1Ns() { return this.add("right-1-ns"); }
get bottom_1Ns() { return this.add("bottom-1-ns"); }
get top_2Ns() { return this.add("top-2-ns"); }
get left_2Ns() { return this.add("left-2-ns"); }
get right_2Ns() { return this.add("right-2-ns"); }
get bottom_2Ns() { return this.add("bottom-2-ns"); }
get absoluteFillNs() { return this.add("absolute--fill-ns"); }
get clNs() { return this.add("cl-ns"); }
get crNs() { return this.add("cr-ns"); }
get cbNs() { return this.add("cb-ns"); }
get cnNs() { return this.add("cn-ns"); }
get dnNs() { return this.add("dn-ns"); }
get diNs() { return this.add("di-ns"); }
get dbNs() { return this.add("db-ns"); }
get dibNs() { return this.add("dib-ns"); }
get ditNs() { return this.add("dit-ns"); }
get dtNs() { return this.add("dt-ns"); }
get dtcNs() { return this.add("dtc-ns"); }
get dtRowNs() { return this.add("dt-row-ns"); }
get dtRowGroupNs() { return this.add("dt-row-group-ns"); }
get dtColumnNs() { return this.add("dt-column-ns"); }
get dtColumnGroupNs() { return this.add("dt-column-group-ns"); }
get dtFixedNs() { return this.add("dt--fixed-ns"); }
get flexNs() { return this.add("flex-ns"); }
get inlineFlexNs() { return this.add("inline-flex-ns"); }
get flexAutoNs() { return this.add("flex-auto-ns"); }
get flexNoneNs() { return this.add("flex-none-ns"); }
get flexColumnNs() { return this.add("flex-column-ns"); }
get flexRowNs() { return this.add("flex-row-ns"); }
get flexWrapNs() { return this.add("flex-wrap-ns"); }
get flexNowrapNs() { return this.add("flex-nowrap-ns"); }
get flexWrapReverseNs() { return this.add("flex-wrap-reverse-ns"); }
get flexColumnReverseNs() { return this.add("flex-column-reverse-ns"); }
get flexRowReverseNs() { return this.add("flex-row-reverse-ns"); }
get itemsStartNs() { return this.add("items-start-ns"); }
get itemsEndNs() { return this.add("items-end-ns"); }
get itemsCenterNs() { return this.add("items-center-ns"); }
get itemsBaselineNs() { return this.add("items-baseline-ns"); }
get itemsStretchNs() { return this.add("items-stretch-ns"); }
get selfStartNs() { return this.add("self-start-ns"); }
get selfEndNs() { return this.add("self-end-ns"); }
get selfCenterNs() { return this.add("self-center-ns"); }
get selfBaselineNs() { return this.add("self-baseline-ns"); }
get selfStretchNs() { return this.add("self-stretch-ns"); }
get justifyStartNs() { return this.add("justify-start-ns"); }
get justifyEndNs() { return this.add("justify-end-ns"); }
get justifyCenterNs() { return this.add("justify-center-ns"); }
get justifyBetweenNs() { return this.add("justify-between-ns"); }
get justifyAroundNs() { return this.add("justify-around-ns"); }
get contentStartNs() { return this.add("content-start-ns"); }
get contentEndNs() { return this.add("content-end-ns"); }
get contentCenterNs() { return this.add("content-center-ns"); }
get contentBetweenNs() { return this.add("content-between-ns"); }
get contentAroundNs() { return this.add("content-around-ns"); }
get contentStretchNs() { return this.add("content-stretch-ns"); }
get order_0Ns() { return this.add("order-0-ns"); }
get order_1Ns() { return this.add("order-1-ns"); }
get order_2Ns() { return this.add("order-2-ns"); }
get order_3Ns() { return this.add("order-3-ns"); }
get order_4Ns() { return this.add("order-4-ns"); }
get order_5Ns() { return this.add("order-5-ns"); }
get order_6Ns() { return this.add("order-6-ns"); }
get order_7Ns() { return this.add("order-7-ns"); }
get order_8Ns() { return this.add("order-8-ns"); }
get orderLastNs() { return this.add("order-last-ns"); }
get flexGrow_0Ns() { return this.add("flex-grow-0-ns"); }
get flexGrow_1Ns() { return this.add("flex-grow-1-ns"); }
get flexShrink_0Ns() { return this.add("flex-shrink-0-ns"); }
get flexShrink_1Ns() { return this.add("flex-shrink-1-ns"); }
get flNs() { return this.add("fl-ns"); }
get frNs() { return this.add("fr-ns"); }
get fnNs() { return this.add("fn-ns"); }
get iNs() { return this.add("i-ns"); }
get fsNormalNs() { return this.add("fs-normal-ns"); }
get normalNs() { return this.add("normal-ns"); }
get bNs() { return this.add("b-ns"); }
get fw1Ns() { return this.add("fw1-ns"); }
get fw2Ns() { return this.add("fw2-ns"); }
get fw3Ns() { return this.add("fw3-ns"); }
get fw4Ns() { return this.add("fw4-ns"); }
get fw5Ns() { return this.add("fw5-ns"); }
get fw6Ns() { return this.add("fw6-ns"); }
get fw7Ns() { return this.add("fw7-ns"); }
get fw8Ns() { return this.add("fw8-ns"); }
get fw9Ns() { return this.add("fw9-ns"); }
get h1Ns() { return this.add("h1-ns"); }
get h2Ns() { return this.add("h2-ns"); }
get h3Ns() { return this.add("h3-ns"); }
get h4Ns() { return this.add("h4-ns"); }
get h5Ns() { return this.add("h5-ns"); }
get h_25Ns() { return this.add("h-25-ns"); }
get h_50Ns() { return this.add("h-50-ns"); }
get h_75Ns() { return this.add("h-75-ns"); }
get h_100Ns() { return this.add("h-100-ns"); }
get minH_100Ns() { return this.add("min-h-100-ns"); }
get vh_25Ns() { return this.add("vh-25-ns"); }
get vh_50Ns() { return this.add("vh-50-ns"); }
get vh_75Ns() { return this.add("vh-75-ns"); }
get vh_100Ns() { return this.add("vh-100-ns"); }
get minVh_100Ns() { return this.add("min-vh-100-ns"); }
get hAutoNs() { return this.add("h-auto-ns"); }
get hInheritNs() { return this.add("h-inherit-ns"); }
get trackedNs() { return this.add("tracked-ns"); }
get trackedTightNs() { return this.add("tracked-tight-ns"); }
get trackedMegaNs() { return this.add("tracked-mega-ns"); }
get lhSolidNs() { return this.add("lh-solid-ns"); }
get lhTitleNs() { return this.add("lh-title-ns"); }
get lhCopyNs() { return this.add("lh-copy-ns"); }
get mw_100Ns() { return this.add("mw-100-ns"); }
get mw1Ns() { return this.add("mw1-ns"); }
get mw2Ns() { return this.add("mw2-ns"); }
get mw3Ns() { return this.add("mw3-ns"); }
get mw4Ns() { return this.add("mw4-ns"); }
get mw5Ns() { return this.add("mw5-ns"); }
get mw6Ns() { return this.add("mw6-ns"); }
get mw7Ns() { return this.add("mw7-ns"); }
get mw8Ns() { return this.add("mw8-ns"); }
get mw9Ns() { return this.add("mw9-ns"); }
get mwNoneNs() { return this.add("mw-none-ns"); }
get w1Ns() { return this.add("w1-ns"); }
get w2Ns() { return this.add("w2-ns"); }
get w3Ns() { return this.add("w3-ns"); }
get w4Ns() { return this.add("w4-ns"); }
get w5Ns() { return this.add("w5-ns"); }
get w_10Ns() { return this.add("w-10-ns"); }
get w_20Ns() { return this.add("w-20-ns"); }
get w_25Ns() { return this.add("w-25-ns"); }
get w_30Ns() { return this.add("w-30-ns"); }
get w_33Ns() { return this.add("w-33-ns"); }
get w_34Ns() { return this.add("w-34-ns"); }
get w_40Ns() { return this.add("w-40-ns"); }
get w_50Ns() { return this.add("w-50-ns"); }
get w_60Ns() { return this.add("w-60-ns"); }
get w_70Ns() { return this.add("w-70-ns"); }
get w_75Ns() { return this.add("w-75-ns"); }
get w_80Ns() { return this.add("w-80-ns"); }
get w_90Ns() { return this.add("w-90-ns"); }
get w_100Ns() { return this.add("w-100-ns"); }
get wThirdNs() { return this.add("w-third-ns"); }
get wTwoThirdsNs() { return this.add("w-two-thirds-ns"); }
get wAutoNs() { return this.add("w-auto-ns"); }
get overflowVisibleNs() { return this.add("overflow-visible-ns"); }
get overflowHiddenNs() { return this.add("overflow-hidden-ns"); }
get overflowScrollNs() { return this.add("overflow-scroll-ns"); }
get overflowAutoNs() { return this.add("overflow-auto-ns"); }
get overflowXVisibleNs() { return this.add("overflow-x-visible-ns"); }
get overflowXHiddenNs() { return this.add("overflow-x-hidden-ns"); }
get overflowXScrollNs() { return this.add("overflow-x-scroll-ns"); }
get overflowXAutoNs() { return this.add("overflow-x-auto-ns"); }
get overflowYVisibleNs() { return this.add("overflow-y-visible-ns"); }
get overflowYHiddenNs() { return this.add("overflow-y-hidden-ns"); }
get overflowYScrollNs() { return this.add("overflow-y-scroll-ns"); }
get overflowYAutoNs() { return this.add("overflow-y-auto-ns"); }
get staticNs() { return this.add("static-ns"); }
get relativeNs() { return this.add("relative-ns"); }
get absoluteNs() { return this.add("absolute-ns"); }
get fixedNs() { return this.add("fixed-ns"); }
get rotate_45Ns() { return this.add("rotate-45-ns"); }
get rotate_90Ns() { return this.add("rotate-90-ns"); }
get rotate_135Ns() { return this.add("rotate-135-ns"); }
get rotate_180Ns() { return this.add("rotate-180-ns"); }
get rotate_225Ns() { return this.add("rotate-225-ns"); }
get rotate_270Ns() { return this.add("rotate-270-ns"); }
get rotate_315Ns() { return this.add("rotate-315-ns"); }
get pa0Ns() { return this.add("pa0-ns"); }
get pa1Ns() { return this.add("pa1-ns"); }
get pa2Ns() { return this.add("pa2-ns"); }
get pa3Ns() { return this.add("pa3-ns"); }
get pa4Ns() { return this.add("pa4-ns"); }
get pa5Ns() { return this.add("pa5-ns"); }
get pa6Ns() { return this.add("pa6-ns"); }
get pa7Ns() { return this.add("pa7-ns"); }
get pl0Ns() { return this.add("pl0-ns"); }
get pl1Ns() { return this.add("pl1-ns"); }
get pl2Ns() { return this.add("pl2-ns"); }
get pl3Ns() { return this.add("pl3-ns"); }
get pl4Ns() { return this.add("pl4-ns"); }
get pl5Ns() { return this.add("pl5-ns"); }
get pl6Ns() { return this.add("pl6-ns"); }
get pl7Ns() { return this.add("pl7-ns"); }
get pr0Ns() { return this.add("pr0-ns"); }
get pr1Ns() { return this.add("pr1-ns"); }
get pr2Ns() { return this.add("pr2-ns"); }
get pr3Ns() { return this.add("pr3-ns"); }
get pr4Ns() { return this.add("pr4-ns"); }
get pr5Ns() { return this.add("pr5-ns"); }
get pr6Ns() { return this.add("pr6-ns"); }
get pr7Ns() { return this.add("pr7-ns"); }
get pb0Ns() { return this.add("pb0-ns"); }
get pb1Ns() { return this.add("pb1-ns"); }
get pb2Ns() { return this.add("pb2-ns"); }
get pb3Ns() { return this.add("pb3-ns"); }
get pb4Ns() { return this.add("pb4-ns"); }
get pb5Ns() { return this.add("pb5-ns"); }
get pb6Ns() { return this.add("pb6-ns"); }
get pb7Ns() { return this.add("pb7-ns"); }
get pt0Ns() { return this.add("pt0-ns"); }
get pt1Ns() { return this.add("pt1-ns"); }
get pt2Ns() { return this.add("pt2-ns"); }
get pt3Ns() { return this.add("pt3-ns"); }
get pt4Ns() { return this.add("pt4-ns"); }
get pt5Ns() { return this.add("pt5-ns"); }
get pt6Ns() { return this.add("pt6-ns"); }
get pt7Ns() { return this.add("pt7-ns"); }
get pv0Ns() { return this.add("pv0-ns"); }
get pv1Ns() { return this.add("pv1-ns"); }
get pv2Ns() { return this.add("pv2-ns"); }
get pv3Ns() { return this.add("pv3-ns"); }
get pv4Ns() { return this.add("pv4-ns"); }
get pv5Ns() { return this.add("pv5-ns"); }
get pv6Ns() { return this.add("pv6-ns"); }
get pv7Ns() { return this.add("pv7-ns"); }
get ph0Ns() { return this.add("ph0-ns"); }
get ph1Ns() { return this.add("ph1-ns"); }
get ph2Ns() { return this.add("ph2-ns"); }
get ph3Ns() { return this.add("ph3-ns"); }
get ph4Ns() { return this.add("ph4-ns"); }
get ph5Ns() { return this.add("ph5-ns"); }
get ph6Ns() { return this.add("ph6-ns"); }
get ph7Ns() { return this.add("ph7-ns"); }
get ma0Ns() { return this.add("ma0-ns"); }
get ma1Ns() { return this.add("ma1-ns"); }
get ma2Ns() { return this.add("ma2-ns"); }
get ma3Ns() { return this.add("ma3-ns"); }
get ma4Ns() { return this.add("ma4-ns"); }
get ma5Ns() { return this.add("ma5-ns"); }
get ma6Ns() { return this.add("ma6-ns"); }
get ma7Ns() { return this.add("ma7-ns"); }
get ml0Ns() { return this.add("ml0-ns"); }
get ml1Ns() { return this.add("ml1-ns"); }
get ml2Ns() { return this.add("ml2-ns"); }
get ml3Ns() { return this.add("ml3-ns"); }
get ml4Ns() { return this.add("ml4-ns"); }
get ml5Ns() { return this.add("ml5-ns"); }
get ml6Ns() { return this.add("ml6-ns"); }
get ml7Ns() { return this.add("ml7-ns"); }
get mr0Ns() { return this.add("mr0-ns"); }
get mr1Ns() { return this.add("mr1-ns"); }
get mr2Ns() { return this.add("mr2-ns"); }
get mr3Ns() { return this.add("mr3-ns"); }
get mr4Ns() { return this.add("mr4-ns"); }
get mr5Ns() { return this.add("mr5-ns"); }
get mr6Ns() { return this.add("mr6-ns"); }
get mr7Ns() { return this.add("mr7-ns"); }
get mb0Ns() { return this.add("mb0-ns"); }
get mb1Ns() { return this.add("mb1-ns"); }
get mb2Ns() { return this.add("mb2-ns"); }
get mb3Ns() { return this.add("mb3-ns"); }
get mb4Ns() { return this.add("mb4-ns"); }
get mb5Ns() { return this.add("mb5-ns"); }
get mb6Ns() { return this.add("mb6-ns"); }
get mb7Ns() { return this.add("mb7-ns"); }
get mt0Ns() { return this.add("mt0-ns"); }
get mt1Ns() { return this.add("mt1-ns"); }
get mt2Ns() { return this.add("mt2-ns"); }
get mt3Ns() { return this.add("mt3-ns"); }
get mt4Ns() { return this.add("mt4-ns"); }
get mt5Ns() { return this.add("mt5-ns"); }
get mt6Ns() { return this.add("mt6-ns"); }
get mt7Ns() { return this.add("mt7-ns"); }
get mv0Ns() { return this.add("mv0-ns"); }
get mv1Ns() { return this.add("mv1-ns"); }
get mv2Ns() { return this.add("mv2-ns"); }
get mv3Ns() { return this.add("mv3-ns"); }
get mv4Ns() { return this.add("mv4-ns"); }
get mv5Ns() { return this.add("mv5-ns"); }
get mv6Ns() { return this.add("mv6-ns"); }
get mv7Ns() { return this.add("mv7-ns"); }
get mh0Ns() { return this.add("mh0-ns"); }
get mh1Ns() { return this.add("mh1-ns"); }
get mh2Ns() { return this.add("mh2-ns"); }
get mh3Ns() { return this.add("mh3-ns"); }
get mh4Ns() { return this.add("mh4-ns"); }
get mh5Ns() { return this.add("mh5-ns"); }
get mh6Ns() { return this.add("mh6-ns"); }
get mh7Ns() { return this.add("mh7-ns"); }
get na1Ns() { return this.add("na1-ns"); }
get na2Ns() { return this.add("na2-ns"); }
get na3Ns() { return this.add("na3-ns"); }
get na4Ns() { return this.add("na4-ns"); }
get na5Ns() { return this.add("na5-ns"); }
get na6Ns() { return this.add("na6-ns"); }
get na7Ns() { return this.add("na7-ns"); }
get nl1Ns() { return this.add("nl1-ns"); }
get nl2Ns() { return this.add("nl2-ns"); }
get nl3Ns() { return this.add("nl3-ns"); }
get nl4Ns() { return this.add("nl4-ns"); }
get nl5Ns() { return this.add("nl5-ns"); }
get nl6Ns() { return this.add("nl6-ns"); }
get nl7Ns() { return this.add("nl7-ns"); }
get nr1Ns() { return this.add("nr1-ns"); }
get nr2Ns() { return this.add("nr2-ns"); }
get nr3Ns() { return this.add("nr3-ns"); }
get nr4Ns() { return this.add("nr4-ns"); }
get nr5Ns() { return this.add("nr5-ns"); }
get nr6Ns() { return this.add("nr6-ns"); }
get nr7Ns() { return this.add("nr7-ns"); }
get nb1Ns() { return this.add("nb1-ns"); }
get nb2Ns() { return this.add("nb2-ns"); }
get nb3Ns() { return this.add("nb3-ns"); }
get nb4Ns() { return this.add("nb4-ns"); }
get nb5Ns() { return this.add("nb5-ns"); }
get nb6Ns() { return this.add("nb6-ns"); }
get nb7Ns() { return this.add("nb7-ns"); }
get nt1Ns() { return this.add("nt1-ns"); }
get nt2Ns() { return this.add("nt2-ns"); }
get nt3Ns() { return this.add("nt3-ns"); }
get nt4Ns() { return this.add("nt4-ns"); }
get nt5Ns() { return this.add("nt5-ns"); }
get nt6Ns() { return this.add("nt6-ns"); }
get nt7Ns() { return this.add("nt7-ns"); }
get strikeNs() { return this.add("strike-ns"); }
get underlineNs() { return this.add("underline-ns"); }
get noUnderlineNs() { return this.add("no-underline-ns"); }
get tlNs() { return this.add("tl-ns"); }
get trNs() { return this.add("tr-ns"); }
get tcNs() { return this.add("tc-ns"); }
get tjNs() { return this.add("tj-ns"); }
get ttcNs() { return this.add("ttc-ns"); }
get ttlNs() { return this.add("ttl-ns"); }
get ttuNs() { return this.add("ttu-ns"); }
get ttnNs() { return this.add("ttn-ns"); }
get f_6Ns() { return this.add("f-6-ns"); }
get fHeadlineNs() { return this.add("f-headline-ns"); }
get f_5Ns() { return this.add("f-5-ns"); }
get fSubheadlineNs() { return this.add("f-subheadline-ns"); }
get f1Ns() { return this.add("f1-ns"); }
get f2Ns() { return this.add("f2-ns"); }
get f3Ns() { return this.add("f3-ns"); }
get f4Ns() { return this.add("f4-ns"); }
get f5Ns() { return this.add("f5-ns"); }
get f6Ns() { return this.add("f6-ns"); }
get f7Ns() { return this.add("f7-ns"); }
get measureNs() { return this.add("measure-ns"); }
get measureWideNs() { return this.add("measure-wide-ns"); }
get measureNarrowNs() { return this.add("measure-narrow-ns"); }
get indentNs() { return this.add("indent-ns"); }
get smallCapsNs() { return this.add("small-caps-ns"); }
get truncateNs() { return this.add("truncate-ns"); }
get centerNs() { return this.add("center-ns"); }
get mrAutoNs() { return this.add("mr-auto-ns"); }
get mlAutoNs() { return this.add("ml-auto-ns"); }
get clipNs() { return this.add("clip-ns"); }
get wsNormalNs() { return this.add("ws-normal-ns"); }
get nowrapNs() { return this.add("nowrap-ns"); }
get preNs() { return this.add("pre-ns"); }
get vBaseNs() { return this.add("v-base-ns"); }
get vMidNs() { return this.add("v-mid-ns"); }
get vTopNs() { return this.add("v-top-ns"); }
get vBtmNs() { return this.add("v-btm-ns"); }
get aspectRatioM() { return this.add("aspect-ratio-m"); }
get aspectRatio_16x9M() { return this.add("aspect-ratio--16x9-m"); }
get aspectRatio_9x16M() { return this.add("aspect-ratio--9x16-m"); }
get aspectRatio_4x3M() { return this.add("aspect-ratio--4x3-m"); }
get aspectRatio_3x4M() { return this.add("aspect-ratio--3x4-m"); }
get aspectRatio_6x4M() { return this.add("aspect-ratio--6x4-m"); }
get aspectRatio_4x6M() { return this.add("aspect-ratio--4x6-m"); }
get aspectRatio_8x5M() { return this.add("aspect-ratio--8x5-m"); }
get aspectRatio_5x8M() { return this.add("aspect-ratio--5x8-m"); }
get aspectRatio_7x5M() { return this.add("aspect-ratio--7x5-m"); }
get aspectRatio_5x7M() { return this.add("aspect-ratio--5x7-m"); }
get aspectRatio_1x1M() { return this.add("aspect-ratio--1x1-m"); }
get aspectRatioObjectM() { return this.add("aspect-ratio--object-m"); }
get coverM() { return this.add("cover-m"); }
get containM() { return this.add("contain-m"); }
get bgCenterM() { return this.add("bg-center-m"); }
get bgTopM() { return this.add("bg-top-m"); }
get bgRightM() { return this.add("bg-right-m"); }
get bgBottomM() { return this.add("bg-bottom-m"); }
get bgLeftM() { return this.add("bg-left-m"); }
get outlineM() { return this.add("outline-m"); }
get outlineTransparentM() { return this.add("outline-transparent-m"); }
get outline_0M() { return this.add("outline-0-m"); }
get baM() { return this.add("ba-m"); }
get btM() { return this.add("bt-m"); }
get brM() { return this.add("br-m"); }
get bbM() { return this.add("bb-m"); }
get blM() { return this.add("bl-m"); }
get bnM() { return this.add("bn-m"); }
get br0M() { return this.add("br0-m"); }
get br1M() { return this.add("br1-m"); }
get br2M() { return this.add("br2-m"); }
get br3M() { return this.add("br3-m"); }
get br4M() { return this.add("br4-m"); }
get br_100M() { return this.add("br-100-m"); }
get brPillM() { return this.add("br-pill-m"); }
get brBottomM() { return this.add("br--bottom-m"); }
get brTopM() { return this.add("br--top-m"); }
get brRightM() { return this.add("br--right-m"); }
get brLeftM() { return this.add("br--left-m"); }
get bDottedM() { return this.add("b--dotted-m"); }
get bDashedM() { return this.add("b--dashed-m"); }
get bSolidM() { return this.add("b--solid-m"); }
get bNoneM() { return this.add("b--none-m"); }
get bw0M() { return this.add("bw0-m"); }
get bw1M() { return this.add("bw1-m"); }
get bw2M() { return this.add("bw2-m"); }
get bw3M() { return this.add("bw3-m"); }
get bw4M() { return this.add("bw4-m"); }
get bw5M() { return this.add("bw5-m"); }
get bt_0M() { return this.add("bt-0-m"); }
get br_0M() { return this.add("br-0-m"); }
get bb_0M() { return this.add("bb-0-m"); }
get bl_0M() { return this.add("bl-0-m"); }
get shadow_1M() { return this.add("shadow-1-m"); }
get shadow_2M() { return this.add("shadow-2-m"); }
get shadow_3M() { return this.add("shadow-3-m"); }
get shadow_4M() { return this.add("shadow-4-m"); }
get shadow_5M() { return this.add("shadow-5-m"); }
get top_0M() { return this.add("top-0-m"); }
get left_0M() { return this.add("left-0-m"); }
get right_0M() { return this.add("right-0-m"); }
get bottom_0M() { return this.add("bottom-0-m"); }
get top_1M() { return this.add("top-1-m"); }
get left_1M() { return this.add("left-1-m"); }
get right_1M() { return this.add("right-1-m"); }
get bottom_1M() { return this.add("bottom-1-m"); }
get top_2M() { return this.add("top-2-m"); }
get left_2M() { return this.add("left-2-m"); }
get right_2M() { return this.add("right-2-m"); }
get bottom_2M() { return this.add("bottom-2-m"); }
get absoluteFillM() { return this.add("absolute--fill-m"); }
get clM() { return this.add("cl-m"); }
get crM() { return this.add("cr-m"); }
get cbM() { return this.add("cb-m"); }
get cnM() { return this.add("cn-m"); }
get dnM() { return this.add("dn-m"); }
get diM() { return this.add("di-m"); }
get dbM() { return this.add("db-m"); }
get dibM() { return this.add("dib-m"); }
get ditM() { return this.add("dit-m"); }
get dtM() { return this.add("dt-m"); }
get dtcM() { return this.add("dtc-m"); }
get dtRowM() { return this.add("dt-row-m"); }
get dtRowGroupM() { return this.add("dt-row-group-m"); }
get dtColumnM() { return this.add("dt-column-m"); }
get dtColumnGroupM() { return this.add("dt-column-group-m"); }
get dtFixedM() { return this.add("dt--fixed-m"); }
get flexM() { return this.add("flex-m"); }
get inlineFlexM() { return this.add("inline-flex-m"); }
get flexAutoM() { return this.add("flex-auto-m"); }
get flexNoneM() { return this.add("flex-none-m"); }
get flexColumnM() { return this.add("flex-column-m"); }
get flexRowM() { return this.add("flex-row-m"); }
get flexWrapM() { return this.add("flex-wrap-m"); }
get flexNowrapM() { return this.add("flex-nowrap-m"); }
get flexWrapReverseM() { return this.add("flex-wrap-reverse-m"); }
get flexColumnReverseM() { return this.add("flex-column-reverse-m"); }
get flexRowReverseM() { return this.add("flex-row-reverse-m"); }
get itemsStartM() { return this.add("items-start-m"); }
get itemsEndM() { return this.add("items-end-m"); }
get itemsCenterM() { return this.add("items-center-m"); }
get itemsBaselineM() { return this.add("items-baseline-m"); }
get itemsStretchM() { return this.add("items-stretch-m"); }
get selfStartM() { return this.add("self-start-m"); }
get selfEndM() { return this.add("self-end-m"); }
get selfCenterM() { return this.add("self-center-m"); }
get selfBaselineM() { return this.add("self-baseline-m"); }
get selfStretchM() { return this.add("self-stretch-m"); }
get justifyStartM() { return this.add("justify-start-m"); }
get justifyEndM() { return this.add("justify-end-m"); }
get justifyCenterM() { return this.add("justify-center-m"); }
get justifyBetweenM() { return this.add("justify-between-m"); }
get justifyAroundM() { return this.add("justify-around-m"); }
get contentStartM() { return this.add("content-start-m"); }
get contentEndM() { return this.add("content-end-m"); }
get contentCenterM() { return this.add("content-center-m"); }
get contentBetweenM() { return this.add("content-between-m"); }
get contentAroundM() { return this.add("content-around-m"); }
get contentStretchM() { return this.add("content-stretch-m"); }
get order_0M() { return this.add("order-0-m"); }
get order_1M() { return this.add("order-1-m"); }
get order_2M() { return this.add("order-2-m"); }
get order_3M() { return this.add("order-3-m"); }
get order_4M() { return this.add("order-4-m"); }
get order_5M() { return this.add("order-5-m"); }
get order_6M() { return this.add("order-6-m"); }
get order_7M() { return this.add("order-7-m"); }
get order_8M() { return this.add("order-8-m"); }
get orderLastM() { return this.add("order-last-m"); }
get flexGrow_0M() { return this.add("flex-grow-0-m"); }
get flexGrow_1M() { return this.add("flex-grow-1-m"); }
get flexShrink_0M() { return this.add("flex-shrink-0-m"); }
get flexShrink_1M() { return this.add("flex-shrink-1-m"); }
get flM() { return this.add("fl-m"); }
get frM() { return this.add("fr-m"); }
get fnM() { return this.add("fn-m"); }
get iM() { return this.add("i-m"); }
get fsNormalM() { return this.add("fs-normal-m"); }
get normalM() { return this.add("normal-m"); }
get bM() { return this.add("b-m"); }
get fw1M() { return this.add("fw1-m"); }
get fw2M() { return this.add("fw2-m"); }
get fw3M() { return this.add("fw3-m"); }
get fw4M() { return this.add("fw4-m"); }
get fw5M() { return this.add("fw5-m"); }
get fw6M() { return this.add("fw6-m"); }
get fw7M() { return this.add("fw7-m"); }
get fw8M() { return this.add("fw8-m"); }
get fw9M() { return this.add("fw9-m"); }
get h1M() { return this.add("h1-m"); }
get h2M() { return this.add("h2-m"); }
get h3M() { return this.add("h3-m"); }
get h4M() { return this.add("h4-m"); }
get h5M() { return this.add("h5-m"); }
get h_25M() { return this.add("h-25-m"); }
get h_50M() { return this.add("h-50-m"); }
get h_75M() { return this.add("h-75-m"); }
get h_100M() { return this.add("h-100-m"); }
get minH_100M() { return this.add("min-h-100-m"); }
get vh_25M() { return this.add("vh-25-m"); }
get vh_50M() { return this.add("vh-50-m"); }
get vh_75M() { return this.add("vh-75-m"); }
get vh_100M() { return this.add("vh-100-m"); }
get minVh_100M() { return this.add("min-vh-100-m"); }
get hAutoM() { return this.add("h-auto-m"); }
get hInheritM() { return this.add("h-inherit-m"); }
get trackedM() { return this.add("tracked-m"); }
get trackedTightM() { return this.add("tracked-tight-m"); }
get trackedMegaM() { return this.add("tracked-mega-m"); }
get lhSolidM() { return this.add("lh-solid-m"); }
get lhTitleM() { return this.add("lh-title-m"); }
get lhCopyM() { return this.add("lh-copy-m"); }
get mw_100M() { return this.add("mw-100-m"); }
get mw1M() { return this.add("mw1-m"); }
get mw2M() { return this.add("mw2-m"); }
get mw3M() { return this.add("mw3-m"); }
get mw4M() { return this.add("mw4-m"); }
get mw5M() { return this.add("mw5-m"); }
get mw6M() { return this.add("mw6-m"); }
get mw7M() { return this.add("mw7-m"); }
get mw8M() { return this.add("mw8-m"); }
get mw9M() { return this.add("mw9-m"); }
get mwNoneM() { return this.add("mw-none-m"); }
get w1M() { return this.add("w1-m"); }
get w2M() { return this.add("w2-m"); }
get w3M() { return this.add("w3-m"); }
get w4M() { return this.add("w4-m"); }
get w5M() { return this.add("w5-m"); }
get w_10M() { return this.add("w-10-m"); }
get w_20M() { return this.add("w-20-m"); }
get w_25M() { return this.add("w-25-m"); }
get w_30M() { return this.add("w-30-m"); }
get w_33M() { return this.add("w-33-m"); }
get w_34M() { return this.add("w-34-m"); }
get w_40M() { return this.add("w-40-m"); }
get w_50M() { return this.add("w-50-m"); }
get w_60M() { return this.add("w-60-m"); }
get w_70M() { return this.add("w-70-m"); }
get w_75M() { return this.add("w-75-m"); }
get w_80M() { return this.add("w-80-m"); }
get w_90M() { return this.add("w-90-m"); }
get w_100M() { return this.add("w-100-m"); }
get wThirdM() { return this.add("w-third-m"); }
get wTwoThirdsM() { return this.add("w-two-thirds-m"); }
get wAutoM() { return this.add("w-auto-m"); }
get overflowVisibleM() { return this.add("overflow-visible-m"); }
get overflowHiddenM() { return this.add("overflow-hidden-m"); }
get overflowScrollM() { return this.add("overflow-scroll-m"); }
get overflowAutoM() { return this.add("overflow-auto-m"); }
get overflowXVisibleM() { return this.add("overflow-x-visible-m"); }
get overflowXHiddenM() { return this.add("overflow-x-hidden-m"); }
get overflowXScrollM() { return this.add("overflow-x-scroll-m"); }
get overflowXAutoM() { return this.add("overflow-x-auto-m"); }
get overflowYVisibleM() { return this.add("overflow-y-visible-m"); }
get overflowYHiddenM() { return this.add("overflow-y-hidden-m"); }
get overflowYScrollM() { return this.add("overflow-y-scroll-m"); }
get overflowYAutoM() { return this.add("overflow-y-auto-m"); }
get staticM() { return this.add("static-m"); }
get relativeM() { return this.add("relative-m"); }
get absoluteM() { return this.add("absolute-m"); }
get fixedM() { return this.add("fixed-m"); }
get rotate_45M() { return this.add("rotate-45-m"); }
get rotate_90M() { return this.add("rotate-90-m"); }
get rotate_135M() { return this.add("rotate-135-m"); }
get rotate_180M() { return this.add("rotate-180-m"); }
get rotate_225M() { return this.add("rotate-225-m"); }
get rotate_270M() { return this.add("rotate-270-m"); }
get rotate_315M() { return this.add("rotate-315-m"); }
get pa0M() { return this.add("pa0-m"); }
get pa1M() { return this.add("pa1-m"); }
get pa2M() { return this.add("pa2-m"); }
get pa3M() { return this.add("pa3-m"); }
get pa4M() { return this.add("pa4-m"); }
get pa5M() { return this.add("pa5-m"); }
get pa6M() { return this.add("pa6-m"); }
get pa7M() { return this.add("pa7-m"); }
get pl0M() { return this.add("pl0-m"); }
get pl1M() { return this.add("pl1-m"); }
get pl2M() { return this.add("pl2-m"); }
get pl3M() { return this.add("pl3-m"); }
get pl4M() { return this.add("pl4-m"); }
get pl5M() { return this.add("pl5-m"); }
get pl6M() { return this.add("pl6-m"); }
get pl7M() { return this.add("pl7-m"); }
get pr0M() { return this.add("pr0-m"); }
get pr1M() { return this.add("pr1-m"); }
get pr2M() { return this.add("pr2-m"); }
get pr3M() { return this.add("pr3-m"); }
get pr4M() { return this.add("pr4-m"); }
get pr5M() { return this.add("pr5-m"); }
get pr6M() { return this.add("pr6-m"); }
get pr7M() { return this.add("pr7-m"); }
get pb0M() { return this.add("pb0-m"); }
get pb1M() { return this.add("pb1-m"); }
get pb2M() { return this.add("pb2-m"); }
get pb3M() { return this.add("pb3-m"); }
get pb4M() { return this.add("pb4-m"); }
get pb5M() { return this.add("pb5-m"); }
get pb6M() { return this.add("pb6-m"); }
get pb7M() { return this.add("pb7-m"); }
get pt0M() { return this.add("pt0-m"); }
get pt1M() { return this.add("pt1-m"); }
get pt2M() { return this.add("pt2-m"); }
get pt3M() { return this.add("pt3-m"); }
get pt4M() { return this.add("pt4-m"); }
get pt5M() { return this.add("pt5-m"); }
get pt6M() { return this.add("pt6-m"); }
get pt7M() { return this.add("pt7-m"); }
get pv0M() { return this.add("pv0-m"); }
get pv1M() { return this.add("pv1-m"); }
get pv2M() { return this.add("pv2-m"); }
get pv3M() { return this.add("pv3-m"); }
get pv4M() { return this.add("pv4-m"); }
get pv5M() { return this.add("pv5-m"); }
get pv6M() { return this.add("pv6-m"); }
get pv7M() { return this.add("pv7-m"); }
get ph0M() { return this.add("ph0-m"); }
get ph1M() { return this.add("ph1-m"); }
get ph2M() { return this.add("ph2-m"); }
get ph3M() { return this.add("ph3-m"); }
get ph4M() { return this.add("ph4-m"); }
get ph5M() { return this.add("ph5-m"); }
get ph6M() { return this.add("ph6-m"); }
get ph7M() { return this.add("ph7-m"); }
get ma0M() { return this.add("ma0-m"); }
get ma1M() { return this.add("ma1-m"); }
get ma2M() { return this.add("ma2-m"); }
get ma3M() { return this.add("ma3-m"); }
get ma4M() { return this.add("ma4-m"); }
get ma5M() { return this.add("ma5-m"); }
get ma6M() { return this.add("ma6-m"); }
get ma7M() { return this.add("ma7-m"); }
get ml0M() { return this.add("ml0-m"); }
get ml1M() { return this.add("ml1-m"); }
get ml2M() { return this.add("ml2-m"); }
get ml3M() { return this.add("ml3-m"); }
get ml4M() { return this.add("ml4-m"); }
get ml5M() { return this.add("ml5-m"); }
get ml6M() { return this.add("ml6-m"); }
get ml7M() { return this.add("ml7-m"); }
get mr0M() { return this.add("mr0-m"); }
get mr1M() { return this.add("mr1-m"); }
get mr2M() { return this.add("mr2-m"); }
get mr3M() { return this.add("mr3-m"); }
get mr4M() { return this.add("mr4-m"); }
get mr5M() { return this.add("mr5-m"); }
get mr6M() { return this.add("mr6-m"); }
get mr7M() { return this.add("mr7-m"); }
get mb0M() { return this.add("mb0-m"); }
get mb1M() { return this.add("mb1-m"); }
get mb2M() { return this.add("mb2-m"); }
get mb3M() { return this.add("mb3-m"); }
get mb4M() { return this.add("mb4-m"); }
get mb5M() { return this.add("mb5-m"); }
get mb6M() { return this.add("mb6-m"); }
get mb7M() { return this.add("mb7-m"); }
get mt0M() { return this.add("mt0-m"); }
get mt1M() { return this.add("mt1-m"); }
get mt2M() { return this.add("mt2-m"); }
get mt3M() { return this.add("mt3-m"); }
get mt4M() { return this.add("mt4-m"); }
get mt5M() { return this.add("mt5-m"); }
get mt6M() { return this.add("mt6-m"); }
get mt7M() { return this.add("mt7-m"); }
get mv0M() { return this.add("mv0-m"); }
get mv1M() { return this.add("mv1-m"); }
get mv2M() { return this.add("mv2-m"); }
get mv3M() { return this.add("mv3-m"); }
get mv4M() { return this.add("mv4-m"); }
get mv5M() { return this.add("mv5-m"); }
get mv6M() { return this.add("mv6-m"); }
get mv7M() { return this.add("mv7-m"); }
get mh0M() { return this.add("mh0-m"); }
get mh1M() { return this.add("mh1-m"); }
get mh2M() { return this.add("mh2-m"); }
get mh3M() { return this.add("mh3-m"); }
get mh4M() { return this.add("mh4-m"); }
get mh5M() { return this.add("mh5-m"); }
get mh6M() { return this.add("mh6-m"); }
get mh7M() { return this.add("mh7-m"); }
get na1M() { return this.add("na1-m"); }
get na2M() { return this.add("na2-m"); }
get na3M() { return this.add("na3-m"); }
get na4M() { return this.add("na4-m"); }
get na5M() { return this.add("na5-m"); }
get na6M() { return this.add("na6-m"); }
get na7M() { return this.add("na7-m"); }
get nl1M() { return this.add("nl1-m"); }
get nl2M() { return this.add("nl2-m"); }
get nl3M() { return this.add("nl3-m"); }
get nl4M() { return this.add("nl4-m"); }
get nl5M() { return this.add("nl5-m"); }
get nl6M() { return this.add("nl6-m"); }
get nl7M() { return this.add("nl7-m"); }
get nr1M() { return this.add("nr1-m"); }
get nr2M() { return this.add("nr2-m"); }
get nr3M() { return this.add("nr3-m"); }
get nr4M() { return this.add("nr4-m"); }
get nr5M() { return this.add("nr5-m"); }
get nr6M() { return this.add("nr6-m"); }
get nr7M() { return this.add("nr7-m"); }
get nb1M() { return this.add("nb1-m"); }
get nb2M() { return this.add("nb2-m"); }
get nb3M() { return this.add("nb3-m"); }
get nb4M() { return this.add("nb4-m"); }
get nb5M() { return this.add("nb5-m"); }
get nb6M() { return this.add("nb6-m"); }
get nb7M() { return this.add("nb7-m"); }
get nt1M() { return this.add("nt1-m"); }
get nt2M() { return this.add("nt2-m"); }
get nt3M() { return this.add("nt3-m"); }
get nt4M() { return this.add("nt4-m"); }
get nt5M() { return this.add("nt5-m"); }
get nt6M() { return this.add("nt6-m"); }
get nt7M() { return this.add("nt7-m"); }
get strikeM() { return this.add("strike-m"); }
get underlineM() { return this.add("underline-m"); }
get noUnderlineM() { return this.add("no-underline-m"); }
get tlM() { return this.add("tl-m"); }
get trM() { return this.add("tr-m"); }
get tcM() { return this.add("tc-m"); }
get tjM() { return this.add("tj-m"); }
get ttcM() { return this.add("ttc-m"); }
get ttlM() { return this.add("ttl-m"); }
get ttuM() { return this.add("ttu-m"); }
get ttnM() { return this.add("ttn-m"); }
get f_6M() { return this.add("f-6-m"); }
get fHeadlineM() { return this.add("f-headline-m"); }
get f_5M() { return this.add("f-5-m"); }
get fSubheadlineM() { return this.add("f-subheadline-m"); }
get f1M() { return this.add("f1-m"); }
get f2M() { return this.add("f2-m"); }
get f3M() { return this.add("f3-m"); }
get f4M() { return this.add("f4-m"); }
get f5M() { return this.add("f5-m"); }
get f6M() { return this.add("f6-m"); }
get f7M() { return this.add("f7-m"); }
get measureM() { return this.add("measure-m"); }
get measureWideM() { return this.add("measure-wide-m"); }
get measureNarrowM() { return this.add("measure-narrow-m"); }
get indentM() { return this.add("indent-m"); }
get smallCapsM() { return this.add("small-caps-m"); }
get truncateM() { return this.add("truncate-m"); }
get centerM() { return this.add("center-m"); }
get mrAutoM() { return this.add("mr-auto-m"); }
get mlAutoM() { return this.add("ml-auto-m"); }
get clipM() { return this.add("clip-m"); }
get wsNormalM() { return this.add("ws-normal-m"); }
get nowrapM() { return this.add("nowrap-m"); }
get preM() { return this.add("pre-m"); }
get vBaseM() { return this.add("v-base-m"); }
get vMidM() { return this.add("v-mid-m"); }
get vTopM() { return this.add("v-top-m"); }
get vBtmM() { return this.add("v-btm-m"); }
get aspectRatioL() { return this.add("aspect-ratio-l"); }
get aspectRatio_16x9L() { return this.add("aspect-ratio--16x9-l"); }
get aspectRatio_9x16L() { return this.add("aspect-ratio--9x16-l"); }
get aspectRatio_4x3L() { return this.add("aspect-ratio--4x3-l"); }
get aspectRatio_3x4L() { return this.add("aspect-ratio--3x4-l"); }
get aspectRatio_6x4L() { return this.add("aspect-ratio--6x4-l"); }
get aspectRatio_4x6L() { return this.add("aspect-ratio--4x6-l"); }
get aspectRatio_8x5L() { return this.add("aspect-ratio--8x5-l"); }
get aspectRatio_5x8L() { return this.add("aspect-ratio--5x8-l"); }
get aspectRatio_7x5L() { return this.add("aspect-ratio--7x5-l"); }
get aspectRatio_5x7L() { return this.add("aspect-ratio--5x7-l"); }
get aspectRatio_1x1L() { return this.add("aspect-ratio--1x1-l"); }
get aspectRatioObjectL() { return this.add("aspect-ratio--object-l"); }
get coverL() { return this.add("cover-l"); }
get containL() { return this.add("contain-l"); }
get bgCenterL() { return this.add("bg-center-l"); }
get bgTopL() { return this.add("bg-top-l"); }
get bgRightL() { return this.add("bg-right-l"); }
get bgBottomL() { return this.add("bg-bottom-l"); }
get bgLeftL() { return this.add("bg-left-l"); }
get outlineL() { return this.add("outline-l"); }
get outlineTransparentL() { return this.add("outline-transparent-l"); }
get outline_0L() { return this.add("outline-0-l"); }
get baL() { return this.add("ba-l"); }
get btL() { return this.add("bt-l"); }
get brL() { return this.add("br-l"); }
get bbL() { return this.add("bb-l"); }
get blL() { return this.add("bl-l"); }
get bnL() { return this.add("bn-l"); }
get br0L() { return this.add("br0-l"); }
get br1L() { return this.add("br1-l"); }
get br2L() { return this.add("br2-l"); }
get br3L() { return this.add("br3-l"); }
get br4L() { return this.add("br4-l"); }
get br_100L() { return this.add("br-100-l"); }
get brPillL() { return this.add("br-pill-l"); }
get brBottomL() { return this.add("br--bottom-l"); }
get brTopL() { return this.add("br--top-l"); }
get brRightL() { return this.add("br--right-l"); }
get brLeftL() { return this.add("br--left-l"); }
get bDottedL() { return this.add("b--dotted-l"); }
get bDashedL() { return this.add("b--dashed-l"); }
get bSolidL() { return this.add("b--solid-l"); }
get bNoneL() { return this.add("b--none-l"); }
get bw0L() { return this.add("bw0-l"); }
get bw1L() { return this.add("bw1-l"); }
get bw2L() { return this.add("bw2-l"); }
get bw3L() { return this.add("bw3-l"); }
get bw4L() { return this.add("bw4-l"); }
get bw5L() { return this.add("bw5-l"); }
get bt_0L() { return this.add("bt-0-l"); }
get br_0L() { return this.add("br-0-l"); }
get bb_0L() { return this.add("bb-0-l"); }
get bl_0L() { return this.add("bl-0-l"); }
get shadow_1L() { return this.add("shadow-1-l"); }
get shadow_2L() { return this.add("shadow-2-l"); }
get shadow_3L() { return this.add("shadow-3-l"); }
get shadow_4L() { return this.add("shadow-4-l"); }
get shadow_5L() { return this.add("shadow-5-l"); }
get top_0L() { return this.add("top-0-l"); }
get left_0L() { return this.add("left-0-l"); }
get right_0L() { return this.add("right-0-l"); }
get bottom_0L() { return this.add("bottom-0-l"); }
get top_1L() { return this.add("top-1-l"); }
get left_1L() { return this.add("left-1-l"); }
get right_1L() { return this.add("right-1-l"); }
get bottom_1L() { return this.add("bottom-1-l"); }
get top_2L() { return this.add("top-2-l"); }
get left_2L() { return this.add("left-2-l"); }
get right_2L() { return this.add("right-2-l"); }
get bottom_2L() { return this.add("bottom-2-l"); }
get absoluteFillL() { return this.add("absolute--fill-l"); }
get clL() { return this.add("cl-l"); }
get crL() { return this.add("cr-l"); }
get cbL() { return this.add("cb-l"); }
get cnL() { return this.add("cn-l"); }
get dnL() { return this.add("dn-l"); }
get diL() { return this.add("di-l"); }
get dbL() { return this.add("db-l"); }
get dibL() { return this.add("dib-l"); }
get ditL() { return this.add("dit-l"); }
get dtL() { return this.add("dt-l"); }
get dtcL() { return this.add("dtc-l"); }
get dtRowL() { return this.add("dt-row-l"); }
get dtRowGroupL() { return this.add("dt-row-group-l"); }
get dtColumnL() { return this.add("dt-column-l"); }
get dtColumnGroupL() { return this.add("dt-column-group-l"); }
get dtFixedL() { return this.add("dt--fixed-l"); }
get flexL() { return this.add("flex-l"); }
get inlineFlexL() { return this.add("inline-flex-l"); }
get flexAutoL() { return this.add("flex-auto-l"); }
get flexNoneL() { return this.add("flex-none-l"); }
get flexColumnL() { return this.add("flex-column-l"); }
get flexRowL() { return this.add("flex-row-l"); }
get flexWrapL() { return this.add("flex-wrap-l"); }
get flexNowrapL() { return this.add("flex-nowrap-l"); }
get flexWrapReverseL() { return this.add("flex-wrap-reverse-l"); }
get flexColumnReverseL() { return this.add("flex-column-reverse-l"); }
get flexRowReverseL() { return this.add("flex-row-reverse-l"); }
get itemsStartL() { return this.add("items-start-l"); }
get itemsEndL() { return this.add("items-end-l"); }
get itemsCenterL() { return this.add("items-center-l"); }
get itemsBaselineL() { return this.add("items-baseline-l"); }
get itemsStretchL() { return this.add("items-stretch-l"); }
get selfStartL() { return this.add("self-start-l"); }
get selfEndL() { return this.add("self-end-l"); }
get selfCenterL() { return this.add("self-center-l"); }
get selfBaselineL() { return this.add("self-baseline-l"); }
get selfStretchL() { return this.add("self-stretch-l"); }
get justifyStartL() { return this.add("justify-start-l"); }
get justifyEndL() { return this.add("justify-end-l"); }
get justifyCenterL() { return this.add("justify-center-l"); }
get justifyBetweenL() { return this.add("justify-between-l"); }
get justifyAroundL() { return this.add("justify-around-l"); }
get contentStartL() { return this.add("content-start-l"); }
get contentEndL() { return this.add("content-end-l"); }
get contentCenterL() { return this.add("content-center-l"); }
get contentBetweenL() { return this.add("content-between-l"); }
get contentAroundL() { return this.add("content-around-l"); }
get contentStretchL() { return this.add("content-stretch-l"); }
get order_0L() { return this.add("order-0-l"); }
get order_1L() { return this.add("order-1-l"); }
get order_2L() { return this.add("order-2-l"); }
get order_3L() { return this.add("order-3-l"); }
get order_4L() { return this.add("order-4-l"); }
get order_5L() { return this.add("order-5-l"); }
get order_6L() { return this.add("order-6-l"); }
get order_7L() { return this.add("order-7-l"); }
get order_8L() { return this.add("order-8-l"); }
get orderLastL() { return this.add("order-last-l"); }
get flexGrow_0L() { return this.add("flex-grow-0-l"); }
get flexGrow_1L() { return this.add("flex-grow-1-l"); }
get flexShrink_0L() { return this.add("flex-shrink-0-l"); }
get flexShrink_1L() { return this.add("flex-shrink-1-l"); }
get flL() { return this.add("fl-l"); }
get frL() { return this.add("fr-l"); }
get fnL() { return this.add("fn-l"); }
get iL() { return this.add("i-l"); }
get fsNormalL() { return this.add("fs-normal-l"); }
get normalL() { return this.add("normal-l"); }
get bL() { return this.add("b-l"); }
get fw1L() { return this.add("fw1-l"); }
get fw2L() { return this.add("fw2-l"); }
get fw3L() { return this.add("fw3-l"); }
get fw4L() { return this.add("fw4-l"); }
get fw5L() { return this.add("fw5-l"); }
get fw6L() { return this.add("fw6-l"); }
get fw7L() { return this.add("fw7-l"); }
get fw8L() { return this.add("fw8-l"); }
get fw9L() { return this.add("fw9-l"); }
get h1L() { return this.add("h1-l"); }
get h2L() { return this.add("h2-l"); }
get h3L() { return this.add("h3-l"); }
get h4L() { return this.add("h4-l"); }
get h5L() { return this.add("h5-l"); }
get h_25L() { return this.add("h-25-l"); }
get h_50L() { return this.add("h-50-l"); }
get h_75L() { return this.add("h-75-l"); }
get h_100L() { return this.add("h-100-l"); }
get minH_100L() { return this.add("min-h-100-l"); }
get vh_25L() { return this.add("vh-25-l"); }
get vh_50L() { return this.add("vh-50-l"); }
get vh_75L() { return this.add("vh-75-l"); }
get vh_100L() { return this.add("vh-100-l"); }
get minVh_100L() { return this.add("min-vh-100-l"); }
get hAutoL() { return this.add("h-auto-l"); }
get hInheritL() { return this.add("h-inherit-l"); }
get trackedL() { return this.add("tracked-l"); }
get trackedTightL() { return this.add("tracked-tight-l"); }
get trackedMegaL() { return this.add("tracked-mega-l"); }
get lhSolidL() { return this.add("lh-solid-l"); }
get lhTitleL() { return this.add("lh-title-l"); }
get lhCopyL() { return this.add("lh-copy-l"); }
get mw_100L() { return this.add("mw-100-l"); }
get mw1L() { return this.add("mw1-l"); }
get mw2L() { return this.add("mw2-l"); }
get mw3L() { return this.add("mw3-l"); }
get mw4L() { return this.add("mw4-l"); }
get mw5L() { return this.add("mw5-l"); }
get mw6L() { return this.add("mw6-l"); }
get mw7L() { return this.add("mw7-l"); }
get mw8L() { return this.add("mw8-l"); }
get mw9L() { return this.add("mw9-l"); }
get mwNoneL() { return this.add("mw-none-l"); }
get w1L() { return this.add("w1-l"); }
get w2L() { return this.add("w2-l"); }
get w3L() { return this.add("w3-l"); }
get w4L() { return this.add("w4-l"); }
get w5L() { return this.add("w5-l"); }
get w_10L() { return this.add("w-10-l"); }
get w_20L() { return this.add("w-20-l"); }
get w_25L() { return this.add("w-25-l"); }
get w_30L() { return this.add("w-30-l"); }
get w_33L() { return this.add("w-33-l"); }
get w_34L() { return this.add("w-34-l"); }
get w_40L() { return this.add("w-40-l"); }
get w_50L() { return this.add("w-50-l"); }
get w_60L() { return this.add("w-60-l"); }
get w_70L() { return this.add("w-70-l"); }
get w_75L() { return this.add("w-75-l"); }
get w_80L() { return this.add("w-80-l"); }
get w_90L() { return this.add("w-90-l"); }
get w_100L() { return this.add("w-100-l"); }
get wThirdL() { return this.add("w-third-l"); }
get wTwoThirdsL() { return this.add("w-two-thirds-l"); }
get wAutoL() { return this.add("w-auto-l"); }
get overflowVisibleL() { return this.add("overflow-visible-l"); }
get overflowHiddenL() { return this.add("overflow-hidden-l"); }
get overflowScrollL() { return this.add("overflow-scroll-l"); }
get overflowAutoL() { return this.add("overflow-auto-l"); }
get overflowXVisibleL() { return this.add("overflow-x-visible-l"); }
get overflowXHiddenL() { return this.add("overflow-x-hidden-l"); }
get overflowXScrollL() { return this.add("overflow-x-scroll-l"); }
get overflowXAutoL() { return this.add("overflow-x-auto-l"); }
get overflowYVisibleL() { return this.add("overflow-y-visible-l"); }
get overflowYHiddenL() { return this.add("overflow-y-hidden-l"); }
get overflowYScrollL() { return this.add("overflow-y-scroll-l"); }
get overflowYAutoL() { return this.add("overflow-y-auto-l"); }
get staticL() { return this.add("static-l"); }
get relativeL() { return this.add("relative-l"); }
get absoluteL() { return this.add("absolute-l"); }
get fixedL() { return this.add("fixed-l"); }
get rotate_45L() { return this.add("rotate-45-l"); }
get rotate_90L() { return this.add("rotate-90-l"); }
get rotate_135L() { return this.add("rotate-135-l"); }
get rotate_180L() { return this.add("rotate-180-l"); }
get rotate_225L() { return this.add("rotate-225-l"); }
get rotate_270L() { return this.add("rotate-270-l"); }
get rotate_315L() { return this.add("rotate-315-l"); }
get pa0L() { return this.add("pa0-l"); }
get pa1L() { return this.add("pa1-l"); }
get pa2L() { return this.add("pa2-l"); }
get pa3L() { return this.add("pa3-l"); }
get pa4L() { return this.add("pa4-l"); }
get pa5L() { return this.add("pa5-l"); }
get pa6L() { return this.add("pa6-l"); }
get pa7L() { return this.add("pa7-l"); }
get pl0L() { return this.add("pl0-l"); }
get pl1L() { return this.add("pl1-l"); }
get pl2L() { return this.add("pl2-l"); }
get pl3L() { return this.add("pl3-l"); }
get pl4L() { return this.add("pl4-l"); }
get pl5L() { return this.add("pl5-l"); }
get pl6L() { return this.add("pl6-l"); }
get pl7L() { return this.add("pl7-l"); }
get pr0L() { return this.add("pr0-l"); }
get pr1L() { return this.add("pr1-l"); }
get pr2L() { return this.add("pr2-l"); }
get pr3L() { return this.add("pr3-l"); }
get pr4L() { return this.add("pr4-l"); }
get pr5L() { return this.add("pr5-l"); }
get pr6L() { return this.add("pr6-l"); }
get pr7L() { return this.add("pr7-l"); }
get pb0L() { return this.add("pb0-l"); }
get pb1L() { return this.add("pb1-l"); }
get pb2L() { return this.add("pb2-l"); }
get pb3L() { return this.add("pb3-l"); }
get pb4L() { return this.add("pb4-l"); }
get pb5L() { return this.add("pb5-l"); }
get pb6L() { return this.add("pb6-l"); }
get pb7L() { return this.add("pb7-l"); }
get pt0L() { return this.add("pt0-l"); }
get pt1L() { return this.add("pt1-l"); }
get pt2L() { return this.add("pt2-l"); }
get pt3L() { return this.add("pt3-l"); }
get pt4L() { return this.add("pt4-l"); }
get pt5L() { return this.add("pt5-l"); }
get pt6L() { return this.add("pt6-l"); }
get pt7L() { return this.add("pt7-l"); }
get pv0L() { return this.add("pv0-l"); }
get pv1L() { return this.add("pv1-l"); }
get pv2L() { return this.add("pv2-l"); }
get pv3L() { return this.add("pv3-l"); }
get pv4L() { return this.add("pv4-l"); }
get pv5L() { return this.add("pv5-l"); }
get pv6L() { return this.add("pv6-l"); }
get pv7L() { return this.add("pv7-l"); }
get ph0L() { return this.add("ph0-l"); }
get ph1L() { return this.add("ph1-l"); }
get ph2L() { return this.add("ph2-l"); }
get ph3L() { return this.add("ph3-l"); }
get ph4L() { return this.add("ph4-l"); }
get ph5L() { return this.add("ph5-l"); }
get ph6L() { return this.add("ph6-l"); }
get ph7L() { return this.add("ph7-l"); }
get ma0L() { return this.add("ma0-l"); }
get ma1L() { return this.add("ma1-l"); }
get ma2L() { return this.add("ma2-l"); }
get ma3L() { return this.add("ma3-l"); }
get ma4L() { return this.add("ma4-l"); }
get ma5L() { return this.add("ma5-l"); }
get ma6L() { return this.add("ma6-l"); }
get ma7L() { return this.add("ma7-l"); }
get ml0L() { return this.add("ml0-l"); }
get ml1L() { return this.add("ml1-l"); }
get ml2L() { return this.add("ml2-l"); }
get ml3L() { return this.add("ml3-l"); }
get ml4L() { return this.add("ml4-l"); }
get ml5L() { return this.add("ml5-l"); }
get ml6L() { return this.add("ml6-l"); }
get ml7L() { return this.add("ml7-l"); }
get mr0L() { return this.add("mr0-l"); }
get mr1L() { return this.add("mr1-l"); }
get mr2L() { return this.add("mr2-l"); }
get mr3L() { return this.add("mr3-l"); }
get mr4L() { return this.add("mr4-l"); }
get mr5L() { return this.add("mr5-l"); }
get mr6L() { return this.add("mr6-l"); }
get mr7L() { return this.add("mr7-l"); }
get mb0L() { return this.add("mb0-l"); }
get mb1L() { return this.add("mb1-l"); }
get mb2L() { return this.add("mb2-l"); }
get mb3L() { return this.add("mb3-l"); }
get mb4L() { return this.add("mb4-l"); }
get mb5L() { return this.add("mb5-l"); }
get mb6L() { return this.add("mb6-l"); }
get mb7L() { return this.add("mb7-l"); }
get mt0L() { return this.add("mt0-l"); }
get mt1L() { return this.add("mt1-l"); }
get mt2L() { return this.add("mt2-l"); }
get mt3L() { return this.add("mt3-l"); }
get mt4L() { return this.add("mt4-l"); }
get mt5L() { return this.add("mt5-l"); }
get mt6L() { return this.add("mt6-l"); }
get mt7L() { return this.add("mt7-l"); }
get mv0L() { return this.add("mv0-l"); }
get mv1L() { return this.add("mv1-l"); }
get mv2L() { return this.add("mv2-l"); }
get mv3L() { return this.add("mv3-l"); }
get mv4L() { return this.add("mv4-l"); }
get mv5L() { return this.add("mv5-l"); }
get mv6L() { return this.add("mv6-l"); }
get mv7L() { return this.add("mv7-l"); }
get mh0L() { return this.add("mh0-l"); }
get mh1L() { return this.add("mh1-l"); }
get mh2L() { return this.add("mh2-l"); }
get mh3L() { return this.add("mh3-l"); }
get mh4L() { return this.add("mh4-l"); }
get mh5L() { return this.add("mh5-l"); }
get mh6L() { return this.add("mh6-l"); }
get mh7L() { return this.add("mh7-l"); }
get na1L() { return this.add("na1-l"); }
get na2L() { return this.add("na2-l"); }
get na3L() { return this.add("na3-l"); }
get na4L() { return this.add("na4-l"); }
get na5L() { return this.add("na5-l"); }
get na6L() { return this.add("na6-l"); }
get na7L() { return this.add("na7-l"); }
get nl1L() { return this.add("nl1-l"); }
get nl2L() { return this.add("nl2-l"); }
get nl3L() { return this.add("nl3-l"); }
get nl4L() { return this.add("nl4-l"); }
get nl5L() { return this.add("nl5-l"); }
get nl6L() { return this.add("nl6-l"); }
get nl7L() { return this.add("nl7-l"); }
get nr1L() { return this.add("nr1-l"); }
get nr2L() { return this.add("nr2-l"); }
get nr3L() { return this.add("nr3-l"); }
get nr4L() { return this.add("nr4-l"); }
get nr5L() { return this.add("nr5-l"); }
get nr6L() { return this.add("nr6-l"); }
get nr7L() { return this.add("nr7-l"); }
get nb1L() { return this.add("nb1-l"); }
get nb2L() { return this.add("nb2-l"); }
get nb3L() { return this.add("nb3-l"); }
get nb4L() { return this.add("nb4-l"); }
get nb5L() { return this.add("nb5-l"); }
get nb6L() { return this.add("nb6-l"); }
get nb7L() { return this.add("nb7-l"); }
get nt1L() { return this.add("nt1-l"); }
get nt2L() { return this.add("nt2-l"); }
get nt3L() { return this.add("nt3-l"); }
get nt4L() { return this.add("nt4-l"); }
get nt5L() { return this.add("nt5-l"); }
get nt6L() { return this.add("nt6-l"); }
get nt7L() { return this.add("nt7-l"); }
get strikeL() { return this.add("strike-l"); }
get underlineL() { return this.add("underline-l"); }
get noUnderlineL() { return this.add("no-underline-l"); }
get tlL() { return this.add("tl-l"); }
get trL() { return this.add("tr-l"); }
get tcL() { return this.add("tc-l"); }
get tjL() { return this.add("tj-l"); }
get ttcL() { return this.add("ttc-l"); }
get ttlL() { return this.add("ttl-l"); }
get ttuL() { return this.add("ttu-l"); }
get ttnL() { return this.add("ttn-l"); }
get f_6L() { return this.add("f-6-l"); }
get fHeadlineL() { return this.add("f-headline-l"); }
get f_5L() { return this.add("f-5-l"); }
get fSubheadlineL() { return this.add("f-subheadline-l"); }
get f1L() { return this.add("f1-l"); }
get f2L() { return this.add("f2-l"); }
get f3L() { return this.add("f3-l"); }
get f4L() { return this.add("f4-l"); }
get f5L() { return this.add("f5-l"); }
get f6L() { return this.add("f6-l"); }
get f7L() { return this.add("f7-l"); }
get measureL() { return this.add("measure-l"); }
get measureWideL() { return this.add("measure-wide-l"); }
get measureNarrowL() { return this.add("measure-narrow-l"); }
get indentL() { return this.add("indent-l"); }
get smallCapsL() { return this.add("small-caps-l"); }
get truncateL() { return this.add("truncate-l"); }
get centerL() { return this.add("center-l"); }
get mrAutoL() { return this.add("mr-auto-l"); }
get mlAutoL() { return this.add("ml-auto-l"); }
get clipL() { return this.add("clip-l"); }
get wsNormalL() { return this.add("ws-normal-l"); }
get nowrapL() { return this.add("nowrap-l"); }
get preL() { return this.add("pre-l"); }
get vBaseL() { return this.add("v-base-l"); }
get vMidL() { return this.add("v-mid-l"); }
get vTopL() { return this.add("v-top-l"); }
get vBtmL() { return this.add("v-btm-l"); }

}

export const $$ = (selector?: string): BaseStyles =>  {
    return new BaseStyles("" + selector || "");
};

export const $ = $$();

